window.esdocSearchIndex = [
  [
    "deep-resource/lib/resource/action.js~action",
    "class/lib/Resource/Action.js~Action.html",
    "<span>Action</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Action.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/exception/cachedrequestexception.js~cachedrequestexception",
    "class/lib/Resource/Exception/CachedRequestException.js~CachedRequestException.html",
    "<span>CachedRequestException</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Exception/CachedRequestException.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/exception/directlambdacalldeniedexception.js~directlambdacalldeniedexception",
    "class/lib/Resource/Exception/DirectLambdaCallDeniedException.js~DirectLambdaCallDeniedException.html",
    "<span>DirectLambdaCallDeniedException</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Exception/DirectLambdaCallDeniedException.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/exception/exception.js~exception",
    "class/lib/Exception/Exception.js~Exception.html",
    "<span>Exception</span> <span class=\"search-result-import-path\">deep-resource/lib/Exception/Exception.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/instance.js~instance",
    "class/lib/Resource/Instance.js~Instance.html",
    "<span>Instance</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Instance.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/lambdaresponse.js~lambdaresponse",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html",
    "<span>LambdaResponse</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/LambdaResponse.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/localrequest.js~localrequest",
    "class/lib/Resource/LocalRequest.js~LocalRequest.html",
    "<span>LocalRequest</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/LocalRequest.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/exception/missingactionexception.js~missingactionexception",
    "class/lib/Resource/Exception/MissingActionException.js~MissingActionException.html",
    "<span>MissingActionException</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Exception/MissingActionException.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/exception/missingcacheimplementationexception.js~missingcacheimplementationexception",
    "class/lib/Resource/Exception/MissingCacheImplementationException.js~MissingCacheImplementationException.html",
    "<span>MissingCacheImplementationException</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Exception/MissingCacheImplementationException.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/exception/missingresourceexception.js~missingresourceexception",
    "class/lib/Exception/MissingResourceException.js~MissingResourceException.html",
    "<span>MissingResourceException</span> <span class=\"search-result-import-path\">deep-resource/lib/Exception/MissingResourceException.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/request.js~request",
    "class/lib/Resource/Request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Request.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource.js~resource",
    "class/lib/Resource.js~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/response.js~response",
    "class/lib/Resource/Response.js~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Response.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/superagentresponse.js~superagentresponse",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html",
    "<span>SuperagentResponse</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/SuperagentResponse.js</span>",
    "class"
  ],
  [
    "deep-resource/lib/resource/exception/unknownmethodexception.js~unknownmethodexception",
    "class/lib/Resource/Exception/UnknownMethodException.js~UnknownMethodException.html",
    "<span>UnknownMethodException</span> <span class=\"search-result-import-path\">deep-resource/lib/Resource/Exception/UnknownMethodException.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/exception/exception.js",
    "file/lib/Exception/Exception.js.html",
    "lib/Exception/Exception.js",
    "file"
  ],
  [
    "lib/exception/exception.js~exception#constructor",
    "class/lib/Exception/Exception.js~Exception.html#instance-constructor-constructor",
    "lib/Exception/Exception.js~Exception#constructor",
    "method"
  ],
  [
    "lib/exception/missingresourceexception.js",
    "file/lib/Exception/MissingResourceException.js.html",
    "lib/Exception/MissingResourceException.js",
    "file"
  ],
  [
    "lib/exception/missingresourceexception.js~missingresourceexception#constructor",
    "class/lib/Exception/MissingResourceException.js~MissingResourceException.html#instance-constructor-constructor",
    "lib/Exception/MissingResourceException.js~MissingResourceException#constructor",
    "method"
  ],
  [
    "lib/resource.js",
    "file/lib/Resource.js.html",
    "lib/Resource.js",
    "file"
  ],
  [
    "lib/resource.js~resource#boot",
    "class/lib/Resource.js~Resource.html#instance-method-boot",
    "lib/Resource.js~Resource#boot",
    "method"
  ],
  [
    "lib/resource.js~resource#constructor",
    "class/lib/Resource.js~Resource.html#instance-constructor-constructor",
    "lib/Resource.js~Resource#constructor",
    "method"
  ],
  [
    "lib/resource.js~resource#get",
    "class/lib/Resource.js~Resource.html#instance-method-get",
    "lib/Resource.js~Resource#get",
    "method"
  ],
  [
    "lib/resource.js~resource#has",
    "class/lib/Resource.js~Resource.html#instance-method-has",
    "lib/Resource.js~Resource#has",
    "method"
  ],
  [
    "lib/resource.js~resource#list",
    "class/lib/Resource.js~Resource.html#instance-get-list",
    "lib/Resource.js~Resource#list",
    "member"
  ],
  [
    "lib/resource/action.js",
    "file/lib/Resource/Action.js.html",
    "lib/Resource/Action.js",
    "file"
  ],
  [
    "lib/resource/action.js~action#constructor",
    "class/lib/Resource/Action.js~Action.html#instance-constructor-constructor",
    "lib/Resource/Action.js~Action#constructor",
    "method"
  ],
  [
    "lib/resource/action.js~action#forceuseridentity",
    "class/lib/Resource/Action.js~Action.html#instance-get-forceUserIdentity",
    "lib/Resource/Action.js~Action#forceUserIdentity",
    "member"
  ],
  [
    "lib/resource/action.js~action#methods",
    "class/lib/Resource/Action.js~Action.html#instance-get-methods",
    "lib/Resource/Action.js~Action#methods",
    "member"
  ],
  [
    "lib/resource/action.js~action#name",
    "class/lib/Resource/Action.js~Action.html#instance-get-name",
    "lib/Resource/Action.js~Action#name",
    "member"
  ],
  [
    "lib/resource/action.js~action#region",
    "class/lib/Resource/Action.js~Action.html#instance-get-region",
    "lib/Resource/Action.js~Action#region",
    "member"
  ],
  [
    "lib/resource/action.js~action#request",
    "class/lib/Resource/Action.js~Action.html#instance-method-request",
    "lib/Resource/Action.js~Action#request",
    "method"
  ],
  [
    "lib/resource/action.js~action#resource",
    "class/lib/Resource/Action.js~Action.html#instance-get-resource",
    "lib/Resource/Action.js~Action#resource",
    "member"
  ],
  [
    "lib/resource/action.js~action#source",
    "class/lib/Resource/Action.js~Action.html#instance-get-source",
    "lib/Resource/Action.js~Action#source",
    "member"
  ],
  [
    "lib/resource/action.js~action#type",
    "class/lib/Resource/Action.js~Action.html#instance-get-type",
    "lib/Resource/Action.js~Action#type",
    "member"
  ],
  [
    "lib/resource/action.js~action.external",
    "class/lib/Resource/Action.js~Action.html#static-get-EXTERNAL",
    "lib/Resource/Action.js~Action.EXTERNAL",
    "member"
  ],
  [
    "lib/resource/action.js~action.http_verbs",
    "class/lib/Resource/Action.js~Action.html#static-get-HTTP_VERBS",
    "lib/Resource/Action.js~Action.HTTP_VERBS",
    "member"
  ],
  [
    "lib/resource/action.js~action.lambda",
    "class/lib/Resource/Action.js~Action.html#static-get-LAMBDA",
    "lib/Resource/Action.js~Action.LAMBDA",
    "member"
  ],
  [
    "lib/resource/exception/cachedrequestexception.js",
    "file/lib/Resource/Exception/CachedRequestException.js.html",
    "lib/Resource/Exception/CachedRequestException.js",
    "file"
  ],
  [
    "lib/resource/exception/cachedrequestexception.js~cachedrequestexception#constructor",
    "class/lib/Resource/Exception/CachedRequestException.js~CachedRequestException.html#instance-constructor-constructor",
    "lib/Resource/Exception/CachedRequestException.js~CachedRequestException#constructor",
    "method"
  ],
  [
    "lib/resource/exception/directlambdacalldeniedexception.js",
    "file/lib/Resource/Exception/DirectLambdaCallDeniedException.js.html",
    "lib/Resource/Exception/DirectLambdaCallDeniedException.js",
    "file"
  ],
  [
    "lib/resource/exception/directlambdacalldeniedexception.js~directlambdacalldeniedexception#constructor",
    "class/lib/Resource/Exception/DirectLambdaCallDeniedException.js~DirectLambdaCallDeniedException.html#instance-constructor-constructor",
    "lib/Resource/Exception/DirectLambdaCallDeniedException.js~DirectLambdaCallDeniedException#constructor",
    "method"
  ],
  [
    "lib/resource/exception/missingactionexception.js",
    "file/lib/Resource/Exception/MissingActionException.js.html",
    "lib/Resource/Exception/MissingActionException.js",
    "file"
  ],
  [
    "lib/resource/exception/missingactionexception.js~missingactionexception#constructor",
    "class/lib/Resource/Exception/MissingActionException.js~MissingActionException.html#instance-constructor-constructor",
    "lib/Resource/Exception/MissingActionException.js~MissingActionException#constructor",
    "method"
  ],
  [
    "lib/resource/exception/missingcacheimplementationexception.js",
    "file/lib/Resource/Exception/MissingCacheImplementationException.js.html",
    "lib/Resource/Exception/MissingCacheImplementationException.js",
    "file"
  ],
  [
    "lib/resource/exception/missingcacheimplementationexception.js~missingcacheimplementationexception#constructor",
    "class/lib/Resource/Exception/MissingCacheImplementationException.js~MissingCacheImplementationException.html#instance-constructor-constructor",
    "lib/Resource/Exception/MissingCacheImplementationException.js~MissingCacheImplementationException#constructor",
    "method"
  ],
  [
    "lib/resource/exception/unknownmethodexception.js",
    "file/lib/Resource/Exception/UnknownMethodException.js.html",
    "lib/Resource/Exception/UnknownMethodException.js",
    "file"
  ],
  [
    "lib/resource/exception/unknownmethodexception.js~unknownmethodexception#constructor",
    "class/lib/Resource/Exception/UnknownMethodException.js~UnknownMethodException.html#instance-constructor-constructor",
    "lib/Resource/Exception/UnknownMethodException.js~UnknownMethodException#constructor",
    "method"
  ],
  [
    "lib/resource/instance.js",
    "file/lib/Resource/Instance.js.html",
    "lib/Resource/Instance.js",
    "file"
  ],
  [
    "lib/resource/instance.js~instance#action",
    "class/lib/Resource/Instance.js~Instance.html#instance-method-action",
    "lib/Resource/Instance.js~Instance#action",
    "method"
  ],
  [
    "lib/resource/instance.js~instance#actions",
    "class/lib/Resource/Instance.js~Instance.html#instance-get-actions",
    "lib/Resource/Instance.js~Instance#actions",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#cache",
    "class/lib/Resource/Instance.js~Instance.html#instance-get-cache",
    "lib/Resource/Instance.js~Instance#cache",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#cache",
    "class/lib/Resource/Instance.js~Instance.html#instance-set-cache",
    "lib/Resource/Instance.js~Instance#cache",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#constructor",
    "class/lib/Resource/Instance.js~Instance.html#instance-constructor-constructor",
    "lib/Resource/Instance.js~Instance#constructor",
    "method"
  ],
  [
    "lib/resource/instance.js~instance#has",
    "class/lib/Resource/Instance.js~Instance.html#instance-method-has",
    "lib/Resource/Instance.js~Instance#has",
    "method"
  ],
  [
    "lib/resource/instance.js~instance#localbackend",
    "class/lib/Resource/Instance.js~Instance.html#instance-set-localBackend",
    "lib/Resource/Instance.js~Instance#localBackend",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#localbackend",
    "class/lib/Resource/Instance.js~Instance.html#instance-get-localBackend",
    "lib/Resource/Instance.js~Instance#localBackend",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#name",
    "class/lib/Resource/Instance.js~Instance.html#instance-get-name",
    "lib/Resource/Instance.js~Instance#name",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#request",
    "class/lib/Resource/Instance.js~Instance.html#instance-method-request",
    "lib/Resource/Instance.js~Instance#request",
    "method"
  ],
  [
    "lib/resource/instance.js~instance#securitycredentials",
    "class/lib/Resource/Instance.js~Instance.html#instance-set-securityCredentials",
    "lib/Resource/Instance.js~Instance#securityCredentials",
    "member"
  ],
  [
    "lib/resource/instance.js~instance#securitycredentials",
    "class/lib/Resource/Instance.js~Instance.html#instance-get-securityCredentials",
    "lib/Resource/Instance.js~Instance#securityCredentials",
    "member"
  ],
  [
    "lib/resource/lambdaresponse.js",
    "file/lib/Resource/LambdaResponse.js.html",
    "lib/Resource/LambdaResponse.js",
    "file"
  ],
  [
    "lib/resource/lambdaresponse.js~lambdaresponse#constructor",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html#instance-constructor-constructor",
    "lib/Resource/LambdaResponse.js~LambdaResponse#constructor",
    "method"
  ],
  [
    "lib/resource/lambdaresponse.js~lambdaresponse#data",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html#instance-get-data",
    "lib/Resource/LambdaResponse.js~LambdaResponse#data",
    "member"
  ],
  [
    "lib/resource/lambdaresponse.js~lambdaresponse#error",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html#instance-get-error",
    "lib/Resource/LambdaResponse.js~LambdaResponse#error",
    "member"
  ],
  [
    "lib/resource/lambdaresponse.js~lambdaresponse#errortype",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html#instance-get-errorType",
    "lib/Resource/LambdaResponse.js~LambdaResponse#errorType",
    "member"
  ],
  [
    "lib/resource/lambdaresponse.js~lambdaresponse#statuscode",
    "class/lib/Resource/LambdaResponse.js~LambdaResponse.html#instance-get-statusCode",
    "lib/Resource/LambdaResponse.js~LambdaResponse#statusCode",
    "member"
  ],
  [
    "lib/resource/localrequest.js",
    "file/lib/Resource/LocalRequest.js.html",
    "lib/Resource/LocalRequest.js",
    "file"
  ],
  [
    "lib/resource/localrequest.js~localrequest#constructor",
    "class/lib/Resource/LocalRequest.js~LocalRequest.html#instance-constructor-constructor",
    "lib/Resource/LocalRequest.js~LocalRequest#constructor",
    "method"
  ],
  [
    "lib/resource/localrequest.js~localrequest.local_lambda_endpoint",
    "class/lib/Resource/LocalRequest.js~LocalRequest.html#static-get-LOCAL_LAMBDA_ENDPOINT",
    "lib/Resource/LocalRequest.js~LocalRequest.LOCAL_LAMBDA_ENDPOINT",
    "member"
  ],
  [
    "lib/resource/request.js",
    "file/lib/Resource/Request.js.html",
    "lib/Resource/Request.js",
    "file"
  ],
  [
    "lib/resource/request.js~request#action",
    "class/lib/Resource/Request.js~Request.html#instance-get-action",
    "lib/Resource/Request.js~Request#action",
    "member"
  ],
  [
    "lib/resource/request.js~request#cache",
    "class/lib/Resource/Request.js~Request.html#instance-method-cache",
    "lib/Resource/Request.js~Request#cache",
    "method"
  ],
  [
    "lib/resource/request.js~request#cacheimpl",
    "class/lib/Resource/Request.js~Request.html#instance-set-cacheImpl",
    "lib/Resource/Request.js~Request#cacheImpl",
    "member"
  ],
  [
    "lib/resource/request.js~request#cacheimpl",
    "class/lib/Resource/Request.js~Request.html#instance-get-cacheImpl",
    "lib/Resource/Request.js~Request#cacheImpl",
    "member"
  ],
  [
    "lib/resource/request.js~request#cachettl",
    "class/lib/Resource/Request.js~Request.html#instance-get-cacheTtl",
    "lib/Resource/Request.js~Request#cacheTtl",
    "member"
  ],
  [
    "lib/resource/request.js~request#cachettl",
    "class/lib/Resource/Request.js~Request.html#instance-set-cacheTtl",
    "lib/Resource/Request.js~Request#cacheTtl",
    "member"
  ],
  [
    "lib/resource/request.js~request#constructor",
    "class/lib/Resource/Request.js~Request.html#instance-constructor-constructor",
    "lib/Resource/Request.js~Request#constructor",
    "method"
  ],
  [
    "lib/resource/request.js~request#disablecache",
    "class/lib/Resource/Request.js~Request.html#instance-method-disableCache",
    "lib/Resource/Request.js~Request#disableCache",
    "method"
  ],
  [
    "lib/resource/request.js~request#enablecache",
    "class/lib/Resource/Request.js~Request.html#instance-method-enableCache",
    "lib/Resource/Request.js~Request#enableCache",
    "method"
  ],
  [
    "lib/resource/request.js~request#getendpointhostregion",
    "class/lib/Resource/Request.js~Request.html#instance-method-getEndpointHostRegion",
    "lib/Resource/Request.js~Request#getEndpointHostRegion",
    "method"
  ],
  [
    "lib/resource/request.js~request#invalidatecache",
    "class/lib/Resource/Request.js~Request.html#instance-method-invalidateCache",
    "lib/Resource/Request.js~Request#invalidateCache",
    "method"
  ],
  [
    "lib/resource/request.js~request#iscached",
    "class/lib/Resource/Request.js~Request.html#instance-get-isCached",
    "lib/Resource/Request.js~Request#isCached",
    "member"
  ],
  [
    "lib/resource/request.js~request#method",
    "class/lib/Resource/Request.js~Request.html#instance-get-method",
    "lib/Resource/Request.js~Request#method",
    "member"
  ],
  [
    "lib/resource/request.js~request#native",
    "class/lib/Resource/Request.js~Request.html#instance-get-native",
    "lib/Resource/Request.js~Request#native",
    "member"
  ],
  [
    "lib/resource/request.js~request#payload",
    "class/lib/Resource/Request.js~Request.html#instance-get-payload",
    "lib/Resource/Request.js~Request#payload",
    "member"
  ],
  [
    "lib/resource/request.js~request#send",
    "class/lib/Resource/Request.js~Request.html#instance-method-send",
    "lib/Resource/Request.js~Request#send",
    "method"
  ],
  [
    "lib/resource/request.js~request#usedirectcall",
    "class/lib/Resource/Request.js~Request.html#instance-method-useDirectCall",
    "lib/Resource/Request.js~Request#useDirectCall",
    "method"
  ],
  [
    "lib/resource/request.js~request.ttl_default",
    "class/lib/Resource/Request.js~Request.html#static-get-TTL_DEFAULT",
    "lib/Resource/Request.js~Request.TTL_DEFAULT",
    "member"
  ],
  [
    "lib/resource/request.js~request.ttl_forever",
    "class/lib/Resource/Request.js~Request.html#static-get-TTL_FOREVER",
    "lib/Resource/Request.js~Request.TTL_FOREVER",
    "member"
  ],
  [
    "lib/resource/request.js~request.ttl_invalidate",
    "class/lib/Resource/Request.js~Request.html#static-get-TTL_INVALIDATE",
    "lib/Resource/Request.js~Request.TTL_INVALIDATE",
    "member"
  ],
  [
    "lib/resource/response.js",
    "file/lib/Resource/Response.js.html",
    "lib/Resource/Response.js",
    "file"
  ],
  [
    "lib/resource/response.js~response#constructor",
    "class/lib/Resource/Response.js~Response.html#instance-constructor-constructor",
    "lib/Resource/Response.js~Response#constructor",
    "method"
  ],
  [
    "lib/resource/response.js~response#data",
    "class/lib/Resource/Response.js~Response.html#instance-get-data",
    "lib/Resource/Response.js~Response#data",
    "member"
  ],
  [
    "lib/resource/response.js~response#error",
    "class/lib/Resource/Response.js~Response.html#instance-get-error",
    "lib/Resource/Response.js~Response#error",
    "member"
  ],
  [
    "lib/resource/response.js~response#iserror",
    "class/lib/Resource/Response.js~Response.html#instance-get-isError",
    "lib/Resource/Response.js~Response#isError",
    "member"
  ],
  [
    "lib/resource/response.js~response#rawdata",
    "class/lib/Resource/Response.js~Response.html#instance-get-rawData",
    "lib/Resource/Response.js~Response#rawData",
    "member"
  ],
  [
    "lib/resource/response.js~response#rawerror",
    "class/lib/Resource/Response.js~Response.html#instance-get-rawError",
    "lib/Resource/Response.js~Response#rawError",
    "member"
  ],
  [
    "lib/resource/response.js~response#request",
    "class/lib/Resource/Response.js~Response.html#instance-get-request",
    "lib/Resource/Response.js~Response#request",
    "member"
  ],
  [
    "lib/resource/response.js~response#statuscode",
    "class/lib/Resource/Response.js~Response.html#instance-get-statusCode",
    "lib/Resource/Response.js~Response#statusCode",
    "member"
  ],
  [
    "lib/resource/superagentresponse.js",
    "file/lib/Resource/SuperagentResponse.js.html",
    "lib/Resource/SuperagentResponse.js",
    "file"
  ],
  [
    "lib/resource/superagentresponse.js~superagentresponse#constructor",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html#instance-constructor-constructor",
    "lib/Resource/SuperagentResponse.js~SuperagentResponse#constructor",
    "method"
  ],
  [
    "lib/resource/superagentresponse.js~superagentresponse#data",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html#instance-get-data",
    "lib/Resource/SuperagentResponse.js~SuperagentResponse#data",
    "member"
  ],
  [
    "lib/resource/superagentresponse.js~superagentresponse#error",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html#instance-get-error",
    "lib/Resource/SuperagentResponse.js~SuperagentResponse#error",
    "member"
  ],
  [
    "lib/resource/superagentresponse.js~superagentresponse#iserror",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html#instance-get-isError",
    "lib/Resource/SuperagentResponse.js~SuperagentResponse#isError",
    "member"
  ],
  [
    "lib/resource/superagentresponse.js~superagentresponse#statuscode",
    "class/lib/Resource/SuperagentResponse.js~SuperagentResponse.html#instance-get-statusCode",
    "lib/Resource/SuperagentResponse.js~SuperagentResponse#statusCode",
    "member"
  ],
  [
    "lib/bootstrap.js",
    "file/lib/bootstrap.js.html",
    "lib/bootstrap.js",
    "file"
  ]
]