window.esdocSearchIndex = [
  [
    "deep-kernel/lib/containeraware.js~containeraware",
    "class/lib/ContainerAware.js~ContainerAware.html",
    "<span>ContainerAware</span> <span class=\"search-result-import-path\">deep-kernel/lib/ContainerAware.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/exception/exception.js~exception",
    "class/lib/Exception/Exception.js~Exception.html",
    "<span>Exception</span> <span class=\"search-result-import-path\">deep-kernel/lib/Exception/Exception.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/microservice/injectable.js~injectable",
    "class/lib/Microservice/Injectable.js~Injectable.html",
    "<span>Injectable</span> <span class=\"search-result-import-path\">deep-kernel/lib/Microservice/Injectable.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/microservice/instance.js~instance",
    "class/lib/Microservice/Instance.js~Instance.html",
    "<span>Instance</span> <span class=\"search-result-import-path\">deep-kernel/lib/Microservice/Instance.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/exception/invaliddeepidentifierexception.js~invaliddeepidentifierexception",
    "class/lib/Exception/InvalidDeepIdentifierException.js~InvalidDeepIdentifierException.html",
    "<span>InvalidDeepIdentifierException</span> <span class=\"search-result-import-path\">deep-kernel/lib/Exception/InvalidDeepIdentifierException.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/kernel.js~kernel",
    "class/lib/Kernel.js~Kernel.html",
    "<span>Kernel</span> <span class=\"search-result-import-path\">deep-kernel/lib/Kernel.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/exception/missingmicroserviceexception.js~missingmicroserviceexception",
    "class/lib/Exception/MissingMicroserviceException.js~MissingMicroserviceException.html",
    "<span>MissingMicroserviceException</span> <span class=\"search-result-import-path\">deep-kernel/lib/Exception/MissingMicroserviceException.js</span>",
    "class"
  ],
  [
    "deep-kernel/lib/microservice/exception/missingworkingmicroserviceexception.js~missingworkingmicroserviceexception",
    "class/lib/Microservice/Exception/MissingWorkingMicroserviceException.js~MissingWorkingMicroserviceException.html",
    "<span>MissingWorkingMicroserviceException</span> <span class=\"search-result-import-path\">deep-kernel/lib/Microservice/Exception/MissingWorkingMicroserviceException.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/containeraware.js",
    "file/lib/ContainerAware.js.html",
    "lib/ContainerAware.js",
    "file"
  ],
  [
    "lib/containeraware.js~containeraware#bind",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-method-bind",
    "lib/ContainerAware.js~ContainerAware#bind",
    "method"
  ],
  [
    "lib/containeraware.js~containeraware#boot",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-method-boot",
    "lib/ContainerAware.js~ContainerAware#boot",
    "method"
  ],
  [
    "lib/containeraware.js~containeraware#constructor",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-constructor-constructor",
    "lib/ContainerAware.js~ContainerAware#constructor",
    "method"
  ],
  [
    "lib/containeraware.js~containeraware#container",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-get-container",
    "lib/ContainerAware.js~ContainerAware#container",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#get",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-method-get",
    "lib/ContainerAware.js~ContainerAware#get",
    "method"
  ],
  [
    "lib/containeraware.js~containeraware#kernel",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-get-kernel",
    "lib/ContainerAware.js~ContainerAware#kernel",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#kernel",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-set-kernel",
    "lib/ContainerAware.js~ContainerAware#kernel",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#localbackend",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-get-localBackend",
    "lib/ContainerAware.js~ContainerAware#localBackend",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#localbackend",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-set-localBackend",
    "lib/ContainerAware.js~ContainerAware#localBackend",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#name",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-get-name",
    "lib/ContainerAware.js~ContainerAware#name",
    "member"
  ],
  [
    "lib/containeraware.js~containeraware#service",
    "class/lib/ContainerAware.js~ContainerAware.html#instance-get-service",
    "lib/ContainerAware.js~ContainerAware#service",
    "member"
  ],
  [
    "lib/exception/exception.js",
    "file/lib/Exception/Exception.js.html",
    "lib/Exception/Exception.js",
    "file"
  ],
  [
    "lib/exception/exception.js~exception#constructor",
    "class/lib/Exception/Exception.js~Exception.html#instance-constructor-constructor",
    "lib/Exception/Exception.js~Exception#constructor",
    "method"
  ],
  [
    "lib/exception/invaliddeepidentifierexception.js",
    "file/lib/Exception/InvalidDeepIdentifierException.js.html",
    "lib/Exception/InvalidDeepIdentifierException.js",
    "file"
  ],
  [
    "lib/exception/invaliddeepidentifierexception.js~invaliddeepidentifierexception#constructor",
    "class/lib/Exception/InvalidDeepIdentifierException.js~InvalidDeepIdentifierException.html#instance-constructor-constructor",
    "lib/Exception/InvalidDeepIdentifierException.js~InvalidDeepIdentifierException#constructor",
    "method"
  ],
  [
    "lib/exception/missingmicroserviceexception.js",
    "file/lib/Exception/MissingMicroserviceException.js.html",
    "lib/Exception/MissingMicroserviceException.js",
    "file"
  ],
  [
    "lib/exception/missingmicroserviceexception.js~missingmicroserviceexception#constructor",
    "class/lib/Exception/MissingMicroserviceException.js~MissingMicroserviceException.html#instance-constructor-constructor",
    "lib/Exception/MissingMicroserviceException.js~MissingMicroserviceException#constructor",
    "method"
  ],
  [
    "lib/kernel.js",
    "file/lib/Kernel.js.html",
    "lib/Kernel.js",
    "file"
  ],
  [
    "lib/kernel.js~kernel#buildid",
    "class/lib/Kernel.js~Kernel.html#instance-get-buildId",
    "lib/Kernel.js~Kernel#buildId",
    "member"
  ],
  [
    "lib/kernel.js~kernel#config",
    "class/lib/Kernel.js~Kernel.html#instance-get-config",
    "lib/Kernel.js~Kernel#config",
    "member"
  ],
  [
    "lib/kernel.js~kernel#constructor",
    "class/lib/Kernel.js~Kernel.html#instance-constructor-constructor",
    "lib/Kernel.js~Kernel#constructor",
    "method"
  ],
  [
    "lib/kernel.js~kernel#container",
    "class/lib/Kernel.js~Kernel.html#instance-get-container",
    "lib/Kernel.js~Kernel#container",
    "member"
  ],
  [
    "lib/kernel.js~kernel#context",
    "class/lib/Kernel.js~Kernel.html#instance-get-context",
    "lib/Kernel.js~Kernel#context",
    "member"
  ],
  [
    "lib/kernel.js~kernel#env",
    "class/lib/Kernel.js~Kernel.html#instance-get-env",
    "lib/Kernel.js~Kernel#env",
    "member"
  ],
  [
    "lib/kernel.js~kernel#get",
    "class/lib/Kernel.js~Kernel.html#instance-method-get",
    "lib/Kernel.js~Kernel#get",
    "method"
  ],
  [
    "lib/kernel.js~kernel#isbackend",
    "class/lib/Kernel.js~Kernel.html#instance-get-isBackend",
    "lib/Kernel.js~Kernel#isBackend",
    "member"
  ],
  [
    "lib/kernel.js~kernel#isfrontend",
    "class/lib/Kernel.js~Kernel.html#instance-get-isFrontend",
    "lib/Kernel.js~Kernel#isFrontend",
    "member"
  ],
  [
    "lib/kernel.js~kernel#isloaded",
    "class/lib/Kernel.js~Kernel.html#instance-get-isLoaded",
    "lib/Kernel.js~Kernel#isLoaded",
    "member"
  ],
  [
    "lib/kernel.js~kernel#islocalhost",
    "class/lib/Kernel.js~Kernel.html#instance-get-isLocalhost",
    "lib/Kernel.js~Kernel#isLocalhost",
    "member"
  ],
  [
    "lib/kernel.js~kernel#load",
    "class/lib/Kernel.js~Kernel.html#instance-method-load",
    "lib/Kernel.js~Kernel#load",
    "method"
  ],
  [
    "lib/kernel.js~kernel#loadfromfile",
    "class/lib/Kernel.js~Kernel.html#instance-method-loadFromFile",
    "lib/Kernel.js~Kernel#loadFromFile",
    "method"
  ],
  [
    "lib/kernel.js~kernel#microservice",
    "class/lib/Kernel.js~Kernel.html#instance-method-microservice",
    "lib/Kernel.js~Kernel#microservice",
    "method"
  ],
  [
    "lib/kernel.js~kernel#microservices",
    "class/lib/Kernel.js~Kernel.html#instance-get-microservices",
    "lib/Kernel.js~Kernel#microservices",
    "member"
  ],
  [
    "lib/kernel.js~kernel#services",
    "class/lib/Kernel.js~Kernel.html#instance-get-services",
    "lib/Kernel.js~Kernel#services",
    "member"
  ],
  [
    "lib/kernel.js~kernel.all_contexts",
    "class/lib/Kernel.js~Kernel.html#static-get-ALL_CONTEXTS",
    "lib/Kernel.js~Kernel.ALL_CONTEXTS",
    "member"
  ],
  [
    "lib/kernel.js~kernel.backend_context",
    "class/lib/Kernel.js~Kernel.html#static-get-BACKEND_CONTEXT",
    "lib/Kernel.js~Kernel.BACKEND_CONTEXT",
    "member"
  ],
  [
    "lib/kernel.js~kernel.config",
    "class/lib/Kernel.js~Kernel.html#static-get-CONFIG",
    "lib/Kernel.js~Kernel.CONFIG",
    "member"
  ],
  [
    "lib/kernel.js~kernel.context",
    "class/lib/Kernel.js~Kernel.html#static-get-CONTEXT",
    "lib/Kernel.js~Kernel.CONTEXT",
    "member"
  ],
  [
    "lib/kernel.js~kernel.containeraware",
    "class/lib/Kernel.js~Kernel.html#static-get-ContainerAware",
    "lib/Kernel.js~Kernel.ContainerAware",
    "member"
  ],
  [
    "lib/kernel.js~kernel.frontend_bootstrap_vector",
    "class/lib/Kernel.js~Kernel.html#static-get-FRONTEND_BOOTSTRAP_VECTOR",
    "lib/Kernel.js~Kernel.FRONTEND_BOOTSTRAP_VECTOR",
    "member"
  ],
  [
    "lib/kernel.js~kernel.frontend_context",
    "class/lib/Kernel.js~Kernel.html#static-get-FRONTEND_CONTEXT",
    "lib/Kernel.js~Kernel.FRONTEND_CONTEXT",
    "member"
  ],
  [
    "lib/kernel.js~kernel.kernel",
    "class/lib/Kernel.js~Kernel.html#static-get-KERNEL",
    "lib/Kernel.js~Kernel.KERNEL",
    "member"
  ],
  [
    "lib/kernel.js~kernel.microservices",
    "class/lib/Kernel.js~Kernel.html#static-get-MICROSERVICES",
    "lib/Kernel.js~Kernel.MICROSERVICES",
    "member"
  ],
  [
    "lib/kernel.js~kernel.microserviceinjectable",
    "class/lib/Kernel.js~Kernel.html#static-get-MicroserviceInjectable",
    "lib/Kernel.js~Kernel.MicroserviceInjectable",
    "member"
  ],
  [
    "lib/microservice/exception/missingworkingmicroserviceexception.js",
    "file/lib/Microservice/Exception/MissingWorkingMicroserviceException.js.html",
    "lib/Microservice/Exception/MissingWorkingMicroserviceException.js",
    "file"
  ],
  [
    "lib/microservice/exception/missingworkingmicroserviceexception.js~missingworkingmicroserviceexception#constructor",
    "class/lib/Microservice/Exception/MissingWorkingMicroserviceException.js~MissingWorkingMicroserviceException.html#instance-constructor-constructor",
    "lib/Microservice/Exception/MissingWorkingMicroserviceException.js~MissingWorkingMicroserviceException#constructor",
    "method"
  ],
  [
    "lib/microservice/injectable.js",
    "file/lib/Microservice/Injectable.js.html",
    "lib/Microservice/Injectable.js",
    "file"
  ],
  [
    "lib/microservice/injectable.js~injectable#bind",
    "class/lib/Microservice/Injectable.js~Injectable.html#instance-method-bind",
    "lib/Microservice/Injectable.js~Injectable#bind",
    "method"
  ],
  [
    "lib/microservice/injectable.js~injectable#constructor",
    "class/lib/Microservice/Injectable.js~Injectable.html#instance-constructor-constructor",
    "lib/Microservice/Injectable.js~Injectable#constructor",
    "method"
  ],
  [
    "lib/microservice/injectable.js~injectable#microservice",
    "class/lib/Microservice/Injectable.js~Injectable.html#instance-get-microservice",
    "lib/Microservice/Injectable.js~Injectable#microservice",
    "member"
  ],
  [
    "lib/microservice/injectable.js~injectable#microservice",
    "class/lib/Microservice/Injectable.js~Injectable.html#instance-set-microservice",
    "lib/Microservice/Injectable.js~Injectable#microservice",
    "member"
  ],
  [
    "lib/microservice/instance.js",
    "file/lib/Microservice/Instance.js.html",
    "lib/Microservice/Instance.js",
    "file"
  ],
  [
    "lib/microservice/instance.js~instance#constructor",
    "class/lib/Microservice/Instance.js~Instance.html#instance-constructor-constructor",
    "lib/Microservice/Instance.js~Instance#constructor",
    "method"
  ],
  [
    "lib/microservice/instance.js~instance#identifier",
    "class/lib/Microservice/Instance.js~Instance.html#instance-get-identifier",
    "lib/Microservice/Instance.js~Instance#identifier",
    "member"
  ],
  [
    "lib/microservice/instance.js~instance#inject",
    "class/lib/Microservice/Instance.js~Instance.html#instance-method-inject",
    "lib/Microservice/Instance.js~Instance#inject",
    "method"
  ],
  [
    "lib/microservice/instance.js~instance#isroot",
    "class/lib/Microservice/Instance.js~Instance.html#instance-get-isRoot",
    "lib/Microservice/Instance.js~Instance#isRoot",
    "member"
  ],
  [
    "lib/microservice/instance.js~instance#isroot",
    "class/lib/Microservice/Instance.js~Instance.html#instance-set-isRoot",
    "lib/Microservice/Instance.js~Instance#isRoot",
    "member"
  ],
  [
    "lib/microservice/instance.js~instance#rawresources",
    "class/lib/Microservice/Instance.js~Instance.html#instance-get-rawResources",
    "lib/Microservice/Instance.js~Instance#rawResources",
    "member"
  ],
  [
    "lib/microservice/instance.js~instance#tostring",
    "class/lib/Microservice/Instance.js~Instance.html#instance-method-toString",
    "lib/Microservice/Instance.js~Instance#toString",
    "method"
  ],
  [
    "lib/microservice/instance.js~instance.createvector",
    "class/lib/Microservice/Instance.js~Instance.html#static-method-createVector",
    "lib/Microservice/Instance.js~Instance.createVector",
    "method"
  ],
  [
    "lib/bootstrap.js",
    "file/lib/bootstrap.js.html",
    "lib/bootstrap.js",
    "file"
  ]
]