fail_on_violations: true

javascript:
  enabled: true
  ignore_file: .houndignore
  config_file: .jshint.airbnb.json # Airbnb linter config taken from https://github.com/airbnb/javascript/blob/master/linters/jshintrc

### IGNORE THIS SECTION ###

haml:
  enabled: false

go:
  enabled: false

python:
  enabled: false

scss:
  enabled: false

ruby:
  enabled: false

coffeescript:
  enabled: false
