fail_on_violations: true

javascript:
  jshint:
    enabled: false
  eslint:
    enabled: true
    config_file: .eslintrc
    ignore_file: .eslintignore

### IGNORE THIS SECTION ###

haml:
  enabled: false

go:
  enabled: false

python:
  enabled: false

scss:
  enabled: false

ruby:
  enabled: false

coffeescript:
  enabled: false