---
$:
  preprocess:
    '$.cnci.token': 'eval'
    '$.cnci.ci.options.user': 'eval'
    '$.cnci.ci.options.token': 'eval'
    '$.cnci.ci.options.jobName': 'eval'
    '$.cnci.ci.options.buildNumber': 'eval'
  cnci:
    token: 'process.env.token'
    ci:
      provider: jenkins
      options:
        user: 'process.env.JENKINS_USER'
        token: 'process.env.JENKINS_TOKEN'
        jobName: 'process.env.JOB_NAME'
        buildNumber: 'process.env.BUILD_NUMBER' 
