window.esdocSearchIndex = [
  [
    "deep-security/lib/exception/authexception.js~authexception",
    "class/lib/Exception/AuthException.js~AuthException.html",
    "<span>AuthException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/AuthException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/createcognitodatasetexception.js~createcognitodatasetexception",
    "class/lib/Exception/CreateCognitoDatasetException.js~CreateCognitoDatasetException.html",
    "<span>CreateCognitoDatasetException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/CreateCognitoDatasetException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/credentialsmanager.js~credentialsmanager",
    "class/lib/CredentialsManager.js~CredentialsManager.html",
    "<span>CredentialsManager</span> <span class=\"search-result-import-path\">deep-security/lib/CredentialsManager.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/describeidentityexception.js~describeidentityexception",
    "class/lib/Exception/DescribeIdentityException.js~DescribeIdentityException.html",
    "<span>DescribeIdentityException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/DescribeIdentityException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/exception.js~exception",
    "class/lib/Exception/Exception.js~Exception.html",
    "<span>Exception</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/Exception.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/getcognitorecordexception.js~getcognitorecordexception",
    "class/lib/Exception/GetCognitoRecordException.js~GetCognitoRecordException.html",
    "<span>GetCognitoRecordException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/GetCognitoRecordException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/identityprovider.js~identityprovider",
    "class/lib/IdentityProvider.js~IdentityProvider.html",
    "<span>IdentityProvider</span> <span class=\"search-result-import-path\">deep-security/lib/IdentityProvider.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/identityprovidermismatchexception.js~identityprovidermismatchexception",
    "class/lib/Exception/IdentityProviderMismatchException.js~IdentityProviderMismatchException.html",
    "<span>IdentityProviderMismatchException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/IdentityProviderMismatchException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/identityprovidertokenexpiredexception.js~identityprovidertokenexpiredexception",
    "class/lib/Exception/IdentityProviderTokenExpiredException.js~IdentityProviderTokenExpiredException.html",
    "<span>IdentityProviderTokenExpiredException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/IdentityProviderTokenExpiredException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/invalidprovideridentityexception.js~invalidprovideridentityexception",
    "class/lib/Exception/InvalidProviderIdentityException.js~InvalidProviderIdentityException.html",
    "<span>InvalidProviderIdentityException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/InvalidProviderIdentityException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/loaduserexception.js~loaduserexception",
    "class/lib/Exception/LoadUserException.js~LoadUserException.html",
    "<span>LoadUserException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/LoadUserException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/localtoken.js~localtoken",
    "class/lib/LocalToken.js~LocalToken.html",
    "<span>LocalToken</span> <span class=\"search-result-import-path\">deep-security/lib/LocalToken.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/missingloginproviderexception.js~missingloginproviderexception",
    "class/lib/Exception/MissingLoginProviderException.js~MissingLoginProviderException.html",
    "<span>MissingLoginProviderException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/MissingLoginProviderException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/putcognitorecordexception.js~putcognitorecordexception",
    "class/lib/Exception/PutCognitoRecordException.js~PutCognitoRecordException.html",
    "<span>PutCognitoRecordException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/PutCognitoRecordException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/security.js~security",
    "class/lib/Security.js~Security.html",
    "<span>Security</span> <span class=\"search-result-import-path\">deep-security/lib/Security.js</span>",
    "class"
  ],
  [
    "deep-security/lib/exception/synchronizecognitodatasetexception.js~synchronizecognitodatasetexception",
    "class/lib/Exception/SynchronizeCognitoDatasetException.js~SynchronizeCognitoDatasetException.html",
    "<span>SynchronizeCognitoDatasetException</span> <span class=\"search-result-import-path\">deep-security/lib/Exception/SynchronizeCognitoDatasetException.js</span>",
    "class"
  ],
  [
    "deep-security/lib/token.js~token",
    "class/lib/Token.js~Token.html",
    "<span>Token</span> <span class=\"search-result-import-path\">deep-security/lib/Token.js</span>",
    "class"
  ],
  [
    "deep-security/lib/userprovider.js~userprovider",
    "class/lib/UserProvider.js~UserProvider.html",
    "<span>UserProvider</span> <span class=\"search-result-import-path\">deep-security/lib/UserProvider.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/credentialsmanager.js",
    "file/lib/CredentialsManager.js.html",
    "lib/CredentialsManager.js",
    "file"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#cognitosyncclient",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-get-cognitoSyncClient",
    "lib/CredentialsManager.js~CredentialsManager#cognitoSyncClient",
    "member"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#constructor",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-constructor-constructor",
    "lib/CredentialsManager.js~CredentialsManager#constructor",
    "method"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#deletecredentials",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-method-deleteCredentials",
    "lib/CredentialsManager.js~CredentialsManager#deleteCredentials",
    "method"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#loadbackendcredentials",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-method-loadBackendCredentials",
    "lib/CredentialsManager.js~CredentialsManager#loadBackendCredentials",
    "method"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#loadfrontendcredentials",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-method-loadFrontendCredentials",
    "lib/CredentialsManager.js~CredentialsManager#loadFrontendCredentials",
    "method"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager#savecredentials",
    "class/lib/CredentialsManager.js~CredentialsManager.html#instance-method-saveCredentials",
    "lib/CredentialsManager.js~CredentialsManager#saveCredentials",
    "method"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager.dataset_name",
    "class/lib/CredentialsManager.js~CredentialsManager.html#static-get-DATASET_NAME",
    "lib/CredentialsManager.js~CredentialsManager.DATASET_NAME",
    "member"
  ],
  [
    "lib/credentialsmanager.js~credentialsmanager.record_name",
    "class/lib/CredentialsManager.js~CredentialsManager.html#static-get-RECORD_NAME",
    "lib/CredentialsManager.js~CredentialsManager.RECORD_NAME",
    "member"
  ],
  [
    "lib/exception/authexception.js",
    "file/lib/Exception/AuthException.js.html",
    "lib/Exception/AuthException.js",
    "file"
  ],
  [
    "lib/exception/authexception.js~authexception#constructor",
    "class/lib/Exception/AuthException.js~AuthException.html#instance-constructor-constructor",
    "lib/Exception/AuthException.js~AuthException#constructor",
    "method"
  ],
  [
    "lib/exception/createcognitodatasetexception.js",
    "file/lib/Exception/CreateCognitoDatasetException.js.html",
    "lib/Exception/CreateCognitoDatasetException.js",
    "file"
  ],
  [
    "lib/exception/createcognitodatasetexception.js~createcognitodatasetexception#constructor",
    "class/lib/Exception/CreateCognitoDatasetException.js~CreateCognitoDatasetException.html#instance-constructor-constructor",
    "lib/Exception/CreateCognitoDatasetException.js~CreateCognitoDatasetException#constructor",
    "method"
  ],
  [
    "lib/exception/describeidentityexception.js",
    "file/lib/Exception/DescribeIdentityException.js.html",
    "lib/Exception/DescribeIdentityException.js",
    "file"
  ],
  [
    "lib/exception/describeidentityexception.js~describeidentityexception#constructor",
    "class/lib/Exception/DescribeIdentityException.js~DescribeIdentityException.html#instance-constructor-constructor",
    "lib/Exception/DescribeIdentityException.js~DescribeIdentityException#constructor",
    "method"
  ],
  [
    "lib/exception/exception.js",
    "file/lib/Exception/Exception.js.html",
    "lib/Exception/Exception.js",
    "file"
  ],
  [
    "lib/exception/exception.js~exception#constructor",
    "class/lib/Exception/Exception.js~Exception.html#instance-constructor-constructor",
    "lib/Exception/Exception.js~Exception#constructor",
    "method"
  ],
  [
    "lib/exception/getcognitorecordexception.js",
    "file/lib/Exception/GetCognitoRecordException.js.html",
    "lib/Exception/GetCognitoRecordException.js",
    "file"
  ],
  [
    "lib/exception/getcognitorecordexception.js~getcognitorecordexception#constructor",
    "class/lib/Exception/GetCognitoRecordException.js~GetCognitoRecordException.html#instance-constructor-constructor",
    "lib/Exception/GetCognitoRecordException.js~GetCognitoRecordException#constructor",
    "method"
  ],
  [
    "lib/exception/identityprovidermismatchexception.js",
    "file/lib/Exception/IdentityProviderMismatchException.js.html",
    "lib/Exception/IdentityProviderMismatchException.js",
    "file"
  ],
  [
    "lib/exception/identityprovidermismatchexception.js~identityprovidermismatchexception#constructor",
    "class/lib/Exception/IdentityProviderMismatchException.js~IdentityProviderMismatchException.html#instance-constructor-constructor",
    "lib/Exception/IdentityProviderMismatchException.js~IdentityProviderMismatchException#constructor",
    "method"
  ],
  [
    "lib/exception/identityprovidertokenexpiredexception.js",
    "file/lib/Exception/IdentityProviderTokenExpiredException.js.html",
    "lib/Exception/IdentityProviderTokenExpiredException.js",
    "file"
  ],
  [
    "lib/exception/identityprovidertokenexpiredexception.js~identityprovidertokenexpiredexception#constructor",
    "class/lib/Exception/IdentityProviderTokenExpiredException.js~IdentityProviderTokenExpiredException.html#instance-constructor-constructor",
    "lib/Exception/IdentityProviderTokenExpiredException.js~IdentityProviderTokenExpiredException#constructor",
    "method"
  ],
  [
    "lib/exception/invalidprovideridentityexception.js",
    "file/lib/Exception/InvalidProviderIdentityException.js.html",
    "lib/Exception/InvalidProviderIdentityException.js",
    "file"
  ],
  [
    "lib/exception/invalidprovideridentityexception.js~invalidprovideridentityexception#constructor",
    "class/lib/Exception/InvalidProviderIdentityException.js~InvalidProviderIdentityException.html#instance-constructor-constructor",
    "lib/Exception/InvalidProviderIdentityException.js~InvalidProviderIdentityException#constructor",
    "method"
  ],
  [
    "lib/exception/loaduserexception.js",
    "file/lib/Exception/LoadUserException.js.html",
    "lib/Exception/LoadUserException.js",
    "file"
  ],
  [
    "lib/exception/loaduserexception.js~loaduserexception#constructor",
    "class/lib/Exception/LoadUserException.js~LoadUserException.html#instance-constructor-constructor",
    "lib/Exception/LoadUserException.js~LoadUserException#constructor",
    "method"
  ],
  [
    "lib/exception/missingloginproviderexception.js",
    "file/lib/Exception/MissingLoginProviderException.js.html",
    "lib/Exception/MissingLoginProviderException.js",
    "file"
  ],
  [
    "lib/exception/missingloginproviderexception.js~missingloginproviderexception#constructor",
    "class/lib/Exception/MissingLoginProviderException.js~MissingLoginProviderException.html#instance-constructor-constructor",
    "lib/Exception/MissingLoginProviderException.js~MissingLoginProviderException#constructor",
    "method"
  ],
  [
    "lib/exception/putcognitorecordexception.js",
    "file/lib/Exception/PutCognitoRecordException.js.html",
    "lib/Exception/PutCognitoRecordException.js",
    "file"
  ],
  [
    "lib/exception/putcognitorecordexception.js~putcognitorecordexception#constructor",
    "class/lib/Exception/PutCognitoRecordException.js~PutCognitoRecordException.html#instance-constructor-constructor",
    "lib/Exception/PutCognitoRecordException.js~PutCognitoRecordException#constructor",
    "method"
  ],
  [
    "lib/exception/synchronizecognitodatasetexception.js",
    "file/lib/Exception/SynchronizeCognitoDatasetException.js.html",
    "lib/Exception/SynchronizeCognitoDatasetException.js",
    "file"
  ],
  [
    "lib/exception/synchronizecognitodatasetexception.js~synchronizecognitodatasetexception#constructor",
    "class/lib/Exception/SynchronizeCognitoDatasetException.js~SynchronizeCognitoDatasetException.html#instance-constructor-constructor",
    "lib/Exception/SynchronizeCognitoDatasetException.js~SynchronizeCognitoDatasetException#constructor",
    "method"
  ],
  [
    "lib/identityprovider.js",
    "file/lib/IdentityProvider.js.html",
    "lib/IdentityProvider.js",
    "file"
  ],
  [
    "lib/identityprovider.js~identityprovider#config",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-method-config",
    "lib/IdentityProvider.js~IdentityProvider#config",
    "method"
  ],
  [
    "lib/identityprovider.js~identityprovider#constructor",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-constructor-constructor",
    "lib/IdentityProvider.js~IdentityProvider#constructor",
    "method"
  ],
  [
    "lib/identityprovider.js~identityprovider#istokenvalid",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-method-isTokenValid",
    "lib/IdentityProvider.js~IdentityProvider#isTokenValid",
    "method"
  ],
  [
    "lib/identityprovider.js~identityprovider#name",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-get-name",
    "lib/IdentityProvider.js~IdentityProvider#name",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider#providers",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-get-providers",
    "lib/IdentityProvider.js~IdentityProvider#providers",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider#tokenexpirationtime",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-get-tokenExpirationTime",
    "lib/IdentityProvider.js~IdentityProvider#tokenExpirationTime",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider#userid",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-get-userId",
    "lib/IdentityProvider.js~IdentityProvider#userId",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider#usertoken",
    "class/lib/IdentityProvider.js~IdentityProvider.html#instance-get-userToken",
    "lib/IdentityProvider.js~IdentityProvider#userToken",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider.aliases",
    "class/lib/IdentityProvider.js~IdentityProvider.html#static-method-ALIASES",
    "lib/IdentityProvider.js~IdentityProvider.ALIASES",
    "method"
  ],
  [
    "lib/identityprovider.js~identityprovider.amazon",
    "class/lib/IdentityProvider.js~IdentityProvider.html#static-get-AMAZON",
    "lib/IdentityProvider.js~IdentityProvider.AMAZON",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider.facebook",
    "class/lib/IdentityProvider.js~IdentityProvider.html#static-get-FACEBOOK",
    "lib/IdentityProvider.js~IdentityProvider.FACEBOOK",
    "member"
  ],
  [
    "lib/identityprovider.js~identityprovider.google",
    "class/lib/IdentityProvider.js~IdentityProvider.html#static-get-GOOGLE",
    "lib/IdentityProvider.js~IdentityProvider.GOOGLE",
    "member"
  ],
  [
    "lib/localtoken.js",
    "file/lib/LocalToken.js.html",
    "lib/LocalToken.js",
    "file"
  ],
  [
    "lib/localtoken.js~localtoken#constructor",
    "class/lib/LocalToken.js~LocalToken.html#instance-constructor-constructor",
    "lib/LocalToken.js~LocalToken#constructor",
    "method"
  ],
  [
    "lib/localtoken.js~localtoken#loadcredentials",
    "class/lib/LocalToken.js~LocalToken.html#instance-method-loadCredentials",
    "lib/LocalToken.js~LocalToken#loadCredentials",
    "method"
  ],
  [
    "lib/security.js",
    "file/lib/Security.js.html",
    "lib/Security.js",
    "file"
  ],
  [
    "lib/security.js~security#anonymouslogin",
    "class/lib/Security.js~Security.html#instance-method-anonymousLogin",
    "lib/Security.js~Security#anonymousLogin",
    "method"
  ],
  [
    "lib/security.js~security#boot",
    "class/lib/Security.js~Security.html#instance-method-boot",
    "lib/Security.js~Security#boot",
    "method"
  ],
  [
    "lib/security.js~security#constructor",
    "class/lib/Security.js~Security.html#instance-constructor-constructor",
    "lib/Security.js~Security#constructor",
    "method"
  ],
  [
    "lib/security.js~security#identitypoolid",
    "class/lib/Security.js~Security.html#instance-get-identityPoolId",
    "lib/Security.js~Security#identityPoolId",
    "member"
  ],
  [
    "lib/security.js~security#login",
    "class/lib/Security.js~Security.html#instance-method-login",
    "lib/Security.js~Security#login",
    "method"
  ],
  [
    "lib/security.js~security#logout",
    "class/lib/Security.js~Security.html#instance-method-logout",
    "lib/Security.js~Security#logout",
    "method"
  ],
  [
    "lib/security.js~security#token",
    "class/lib/Security.js~Security.html#instance-get-token",
    "lib/Security.js~Security#token",
    "member"
  ],
  [
    "lib/security.js~security#userprovider",
    "class/lib/Security.js~Security.html#instance-get-userProvider",
    "lib/Security.js~Security#userProvider",
    "member"
  ],
  [
    "lib/security.js~security#warmupbackendlogin",
    "class/lib/Security.js~Security.html#instance-method-warmupBackendLogin",
    "lib/Security.js~Security#warmupBackendLogin",
    "method"
  ],
  [
    "lib/token.js",
    "file/lib/Token.js.html",
    "lib/Token.js",
    "file"
  ],
  [
    "lib/token.js~token#constructor",
    "class/lib/Token.js~Token.html#instance-constructor-constructor",
    "lib/Token.js~Token#constructor",
    "method"
  ],
  [
    "lib/token.js~token#credentials",
    "class/lib/Token.js~Token.html#instance-get-credentials",
    "lib/Token.js~Token#credentials",
    "member"
  ],
  [
    "lib/token.js~token#destroy",
    "class/lib/Token.js~Token.html#instance-method-destroy",
    "lib/Token.js~Token#destroy",
    "method"
  ],
  [
    "lib/token.js~token#getcredentialsexpiredatetime",
    "class/lib/Token.js~Token.html#instance-method-getCredentialsExpireDateTime",
    "lib/Token.js~Token#getCredentialsExpireDateTime",
    "method"
  ],
  [
    "lib/token.js~token#getuser",
    "class/lib/Token.js~Token.html#instance-method-getUser",
    "lib/Token.js~Token#getUser",
    "method"
  ],
  [
    "lib/token.js~token#identityid",
    "class/lib/Token.js~Token.html#instance-get-identityId",
    "lib/Token.js~Token#identityId",
    "member"
  ],
  [
    "lib/token.js~token#identityprovider",
    "class/lib/Token.js~Token.html#instance-set-identityProvider",
    "lib/Token.js~Token#identityProvider",
    "member"
  ],
  [
    "lib/token.js~token#identityprovider",
    "class/lib/Token.js~Token.html#instance-get-identityProvider",
    "lib/Token.js~Token#identityProvider",
    "member"
  ],
  [
    "lib/token.js~token#isanonymous",
    "class/lib/Token.js~Token.html#instance-get-isAnonymous",
    "lib/Token.js~Token#isAnonymous",
    "member"
  ],
  [
    "lib/token.js~token#lambdacontext",
    "class/lib/Token.js~Token.html#instance-set-lambdaContext",
    "lib/Token.js~Token#lambdaContext",
    "member"
  ],
  [
    "lib/token.js~token#lambdacontext",
    "class/lib/Token.js~Token.html#instance-get-lambdaContext",
    "lib/Token.js~Token#lambdaContext",
    "member"
  ],
  [
    "lib/token.js~token#loadcredentials",
    "class/lib/Token.js~Token.html#instance-method-loadCredentials",
    "lib/Token.js~Token#loadCredentials",
    "method"
  ],
  [
    "lib/token.js~token#registertokenexpiredcallback",
    "class/lib/Token.js~Token.html#instance-method-registerTokenExpiredCallback",
    "lib/Token.js~Token#registerTokenExpiredCallback",
    "method"
  ],
  [
    "lib/token.js~token#userprovider",
    "class/lib/Token.js~Token.html#instance-set-userProvider",
    "lib/Token.js~Token#userProvider",
    "member"
  ],
  [
    "lib/token.js~token#validcredentials",
    "class/lib/Token.js~Token.html#instance-method-validCredentials",
    "lib/Token.js~Token#validCredentials",
    "method"
  ],
  [
    "lib/token.js~token.create",
    "class/lib/Token.js~Token.html#static-method-create",
    "lib/Token.js~Token.create",
    "method"
  ],
  [
    "lib/token.js~token.createfromidentityprovider",
    "class/lib/Token.js~Token.html#static-method-createFromIdentityProvider",
    "lib/Token.js~Token.createFromIdentityProvider",
    "method"
  ],
  [
    "lib/token.js~token.createfromlambdacontext",
    "class/lib/Token.js~Token.html#static-method-createFromLambdaContext",
    "lib/Token.js~Token.createFromLambdaContext",
    "method"
  ],
  [
    "lib/token.js~token.getregionfromidentitypoolid",
    "class/lib/Token.js~Token.html#static-method-getRegionFromIdentityPoolId",
    "lib/Token.js~Token.getRegionFromIdentityPoolId",
    "method"
  ],
  [
    "lib/userprovider.js",
    "file/lib/UserProvider.js.html",
    "lib/UserProvider.js",
    "file"
  ],
  [
    "lib/userprovider.js~userprovider#constructor",
    "class/lib/UserProvider.js~UserProvider.html#instance-constructor-constructor",
    "lib/UserProvider.js~UserProvider#constructor",
    "method"
  ],
  [
    "lib/userprovider.js~userprovider#loaduserbyidentityid",
    "class/lib/UserProvider.js~UserProvider.html#instance-method-loadUserByIdentityId",
    "lib/UserProvider.js~UserProvider#loadUserByIdentityId",
    "method"
  ],
  [
    "lib/bootstrap.js",
    "file/lib/bootstrap.js.html",
    "lib/bootstrap.js",
    "file"
  ]
]