window.esdocSearchIndex = [
  [
    "deep-core/lib/aws/iam/action.js~action",
    "class/lib/AWS/IAM/Action.js~Action.html",
    "<span>Action</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Action.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/collection.js~collection",
    "class/lib/AWS/IAM/Collection.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Collection.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/context.js~context",
    "class/lib/AWS/Lambda/Context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Context.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/exception/contextalreadysentexception.js~contextalreadysentexception",
    "class/lib/AWS/Lambda/Exception/ContextAlreadySentException.js~ContextAlreadySentException.html",
    "<span>ContextAlreadySentException</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Exception/ContextAlreadySentException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/exception/databaseoperationexception.js~databaseoperationexception",
    "class/lib/Exception/DatabaseOperationException.js~DatabaseOperationException.html",
    "<span>DatabaseOperationException</span> <span class=\"search-result-import-path\">deep-core/lib/Exception/DatabaseOperationException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/errorresponse.js~errorresponse",
    "class/lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.html",
    "<span>ErrorResponse</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/ErrorResponse.js</span>",
    "class"
  ],
  [
    "deep-core/lib/exception/exception.js~exception",
    "class/lib/Exception/Exception.js~Exception.html",
    "<span>Exception</span> <span class=\"search-result-import-path\">deep-core/lib/Exception/Exception.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/extractable.js~extractable",
    "class/lib/AWS/IAM/Extractable.js~Extractable.html",
    "<span>Extractable</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Extractable.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/factory.js~factory",
    "class/lib/AWS/IAM/Factory.js~Factory.html",
    "<span>Factory</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Factory.js</span>",
    "class"
  ],
  [
    "deep-core/lib/oop/interface.js~interface",
    "class/lib/OOP/Interface.js~Interface.html",
    "<span>Interface</span> <span class=\"search-result-import-path\">deep-core/lib/OOP/Interface.js</span>",
    "class"
  ],
  [
    "deep-core/lib/exception/invalidargumentexception.js~invalidargumentexception",
    "class/lib/Exception/InvalidArgumentException.js~InvalidArgumentException.html",
    "<span>InvalidArgumentException</span> <span class=\"search-result-import-path\">deep-core/lib/Exception/InvalidArgumentException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/exception/invalidarnexception.js~invalidarnexception",
    "class/lib/AWS/IAM/Exception/InvalidArnException.js~InvalidArnException.html",
    "<span>InvalidArnException</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Exception/InvalidArnException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/exception/invalidcognitoidentityexception.js~invalidcognitoidentityexception",
    "class/lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js~InvalidCognitoIdentityException.html",
    "<span>InvalidCognitoIdentityException</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/exception/methodsnotimplementedexception.js~methodsnotimplementedexception",
    "class/lib/Exception/MethodsNotImplementedException.js~MethodsNotImplementedException.html",
    "<span>MethodsNotImplementedException</span> <span class=\"search-result-import-path\">deep-core/lib/Exception/MethodsNotImplementedException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/generic/methodsproxy.js~methodsproxy",
    "class/lib/Generic/MethodsProxy.js~MethodsProxy.html",
    "<span>MethodsProxy</span> <span class=\"search-result-import-path\">deep-core/lib/Generic/MethodsProxy.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/exception/missingruntimecontextexception.js~missingruntimecontextexception",
    "class/lib/AWS/Lambda/Exception/MissingRuntimeContextException.js~MissingRuntimeContextException.html",
    "<span>MissingRuntimeContextException</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Exception/MissingRuntimeContextException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/exception/missingusercontextexception.js~missingusercontextexception",
    "class/lib/AWS/Lambda/Exception/MissingUserContextException.js~MissingUserContextException.html",
    "<span>MissingUserContextException</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Exception/MissingUserContextException.js</span>",
    "class"
  ],
  [
    "deep-core/lib/generic/objectstorage.js~objectstorage",
    "class/lib/Generic/ObjectStorage.js~ObjectStorage.html",
    "<span>ObjectStorage</span> <span class=\"search-result-import-path\">deep-core/lib/Generic/ObjectStorage.js</span>",
    "class"
  ],
  [
    "deep-core/lib/generic/objectvector.js~objectvector",
    "class/lib/Generic/ObjectVector.js~ObjectVector.html",
    "<span>ObjectVector</span> <span class=\"search-result-import-path\">deep-core/lib/Generic/ObjectVector.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/policy.js~policy",
    "class/lib/AWS/IAM/Policy.js~Policy.html",
    "<span>Policy</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Policy.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/region.js~region",
    "class/lib/AWS/Region.js~Region.html",
    "<span>Region</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Region.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/request.js~request",
    "class/lib/AWS/Lambda/Request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Request.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/resource.js~resource",
    "class/lib/AWS/IAM/Resource.js~Resource.html",
    "<span>Resource</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Resource.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/response.js~response",
    "class/lib/AWS/Lambda/Response.js~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Response.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/lambda/runtime.js~runtime",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html",
    "<span>Runtime</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Lambda/Runtime.js</span>",
    "class"
  ],
  [
    "deep-core/lib/runtime/sandbox.js~sandbox",
    "class/lib/Runtime/Sandbox.js~Sandbox.html",
    "<span>Sandbox</span> <span class=\"search-result-import-path\">deep-core/lib/Runtime/Sandbox.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/service.js~service",
    "class/lib/AWS/Service.js~Service.html",
    "<span>Service</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/Service.js</span>",
    "class"
  ],
  [
    "deep-core/lib/aws/iam/statement.js~statement",
    "class/lib/AWS/IAM/Statement.js~Statement.html",
    "<span>Statement</span> <span class=\"search-result-import-path\">deep-core/lib/AWS/IAM/Statement.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/aws/iam/action.js",
    "file/lib/AWS/IAM/Action.js.html",
    "lib/AWS/IAM/Action.js",
    "file"
  ],
  [
    "lib/aws/iam/action.js~action#action",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-get-action",
    "lib/AWS/IAM/Action.js~Action#action",
    "member"
  ],
  [
    "lib/aws/iam/action.js~action#action",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-set-action",
    "lib/AWS/IAM/Action.js~Action#action",
    "member"
  ],
  [
    "lib/aws/iam/action.js~action#constructor",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-constructor-constructor",
    "lib/AWS/IAM/Action.js~Action#constructor",
    "method"
  ],
  [
    "lib/aws/iam/action.js~action#extract",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-method-extract",
    "lib/AWS/IAM/Action.js~Action#extract",
    "method"
  ],
  [
    "lib/aws/iam/action.js~action#service",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-get-service",
    "lib/AWS/IAM/Action.js~Action#service",
    "member"
  ],
  [
    "lib/aws/iam/action.js~action#service",
    "class/lib/AWS/IAM/Action.js~Action.html#instance-set-service",
    "lib/AWS/IAM/Action.js~Action#service",
    "member"
  ],
  [
    "lib/aws/iam/collection.js",
    "file/lib/AWS/IAM/Collection.js.html",
    "lib/AWS/IAM/Collection.js",
    "file"
  ],
  [
    "lib/aws/iam/collection.js~collection#add",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-method-add",
    "lib/AWS/IAM/Collection.js~Collection#add",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#constructor",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-constructor-constructor",
    "lib/AWS/IAM/Collection.js~Collection#constructor",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#count",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-method-count",
    "lib/AWS/IAM/Collection.js~Collection#count",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#create",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-method-create",
    "lib/AWS/IAM/Collection.js~Collection#create",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#extract",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-method-extract",
    "lib/AWS/IAM/Collection.js~Collection#extract",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#list",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-method-list",
    "lib/AWS/IAM/Collection.js~Collection#list",
    "method"
  ],
  [
    "lib/aws/iam/collection.js~collection#prototype",
    "class/lib/AWS/IAM/Collection.js~Collection.html#instance-get-prototype",
    "lib/AWS/IAM/Collection.js~Collection#prototype",
    "member"
  ],
  [
    "lib/aws/iam/exception/invalidarnexception.js",
    "file/lib/AWS/IAM/Exception/InvalidArnException.js.html",
    "lib/AWS/IAM/Exception/InvalidArnException.js",
    "file"
  ],
  [
    "lib/aws/iam/exception/invalidarnexception.js~invalidarnexception#constructor",
    "class/lib/AWS/IAM/Exception/InvalidArnException.js~InvalidArnException.html#instance-constructor-constructor",
    "lib/AWS/IAM/Exception/InvalidArnException.js~InvalidArnException#constructor",
    "method"
  ],
  [
    "lib/aws/iam/extractable.js",
    "file/lib/AWS/IAM/Extractable.js.html",
    "lib/AWS/IAM/Extractable.js",
    "file"
  ],
  [
    "lib/aws/iam/extractable.js~extractable#constructor",
    "class/lib/AWS/IAM/Extractable.js~Extractable.html#instance-constructor-constructor",
    "lib/AWS/IAM/Extractable.js~Extractable#constructor",
    "method"
  ],
  [
    "lib/aws/iam/factory.js",
    "file/lib/AWS/IAM/Factory.js.html",
    "lib/AWS/IAM/Factory.js",
    "file"
  ],
  [
    "lib/aws/iam/factory.js~factory.action",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-get-ACTION",
    "lib/AWS/IAM/Factory.js~Factory.ACTION",
    "member"
  ],
  [
    "lib/aws/iam/factory.js~factory.policy",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-get-POLICY",
    "lib/AWS/IAM/Factory.js~Factory.POLICY",
    "member"
  ],
  [
    "lib/aws/iam/factory.js~factory.resource",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-get-RESOURCE",
    "lib/AWS/IAM/Factory.js~Factory.RESOURCE",
    "member"
  ],
  [
    "lib/aws/iam/factory.js~factory.statement",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-get-STATEMENT",
    "lib/AWS/IAM/Factory.js~Factory.STATEMENT",
    "member"
  ],
  [
    "lib/aws/iam/factory.js~factory.create",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-method-create",
    "lib/AWS/IAM/Factory.js~Factory.create",
    "method"
  ],
  [
    "lib/aws/iam/factory.js~factory.createcollection",
    "class/lib/AWS/IAM/Factory.js~Factory.html#static-method-createCollection",
    "lib/AWS/IAM/Factory.js~Factory.createCollection",
    "method"
  ],
  [
    "lib/aws/iam/policy.js",
    "file/lib/AWS/IAM/Policy.js.html",
    "lib/AWS/IAM/Policy.js",
    "file"
  ],
  [
    "lib/aws/iam/policy.js~policy#constructor",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-constructor-constructor",
    "lib/AWS/IAM/Policy.js~Policy#constructor",
    "method"
  ],
  [
    "lib/aws/iam/policy.js~policy#extract",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-method-extract",
    "lib/AWS/IAM/Policy.js~Policy#extract",
    "method"
  ],
  [
    "lib/aws/iam/policy.js~policy#statement",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-get-statement",
    "lib/AWS/IAM/Policy.js~Policy#statement",
    "member"
  ],
  [
    "lib/aws/iam/policy.js~policy#tostring",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-method-toString",
    "lib/AWS/IAM/Policy.js~Policy#toString",
    "method"
  ],
  [
    "lib/aws/iam/policy.js~policy#version",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-set-version",
    "lib/AWS/IAM/Policy.js~Policy#version",
    "member"
  ],
  [
    "lib/aws/iam/policy.js~policy#version",
    "class/lib/AWS/IAM/Policy.js~Policy.html#instance-get-version",
    "lib/AWS/IAM/Policy.js~Policy#version",
    "member"
  ],
  [
    "lib/aws/iam/policy.js~policy.any",
    "class/lib/AWS/IAM/Policy.js~Policy.html#static-get-ANY",
    "lib/AWS/IAM/Policy.js~Policy.ANY",
    "member"
  ],
  [
    "lib/aws/iam/policy.js~policy.default_version",
    "class/lib/AWS/IAM/Policy.js~Policy.html#static-get-DEFAULT_VERSION",
    "lib/AWS/IAM/Policy.js~Policy.DEFAULT_VERSION",
    "member"
  ],
  [
    "lib/aws/iam/resource.js",
    "file/lib/AWS/IAM/Resource.js.html",
    "lib/AWS/IAM/Resource.js",
    "file"
  ],
  [
    "lib/aws/iam/resource.js~resource#accountid",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-set-accountId",
    "lib/AWS/IAM/Resource.js~Resource#accountId",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#accountid",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-get-accountId",
    "lib/AWS/IAM/Resource.js~Resource#accountId",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#constructor",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-constructor-constructor",
    "lib/AWS/IAM/Resource.js~Resource#constructor",
    "method"
  ],
  [
    "lib/aws/iam/resource.js~resource#descriptor",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-get-descriptor",
    "lib/AWS/IAM/Resource.js~Resource#descriptor",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#descriptor",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-set-descriptor",
    "lib/AWS/IAM/Resource.js~Resource#descriptor",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#extract",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-method-extract",
    "lib/AWS/IAM/Resource.js~Resource#extract",
    "method"
  ],
  [
    "lib/aws/iam/resource.js~resource#region",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-get-region",
    "lib/AWS/IAM/Resource.js~Resource#region",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#region",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-set-region",
    "lib/AWS/IAM/Resource.js~Resource#region",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#service",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-get-service",
    "lib/AWS/IAM/Resource.js~Resource#service",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#service",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-set-service",
    "lib/AWS/IAM/Resource.js~Resource#service",
    "member"
  ],
  [
    "lib/aws/iam/resource.js~resource#updatefromarn",
    "class/lib/AWS/IAM/Resource.js~Resource.html#instance-method-updateFromArn",
    "lib/AWS/IAM/Resource.js~Resource#updateFromArn",
    "method"
  ],
  [
    "lib/aws/iam/statement.js",
    "file/lib/AWS/IAM/Statement.js.html",
    "lib/AWS/IAM/Statement.js",
    "file"
  ],
  [
    "lib/aws/iam/statement.js~statement#action",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-action",
    "lib/AWS/IAM/Statement.js~Statement#action",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#condition",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-condition",
    "lib/AWS/IAM/Statement.js~Statement#condition",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#condition",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-set-condition",
    "lib/AWS/IAM/Statement.js~Statement#condition",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#constructor",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-constructor-constructor",
    "lib/AWS/IAM/Statement.js~Statement#constructor",
    "method"
  ],
  [
    "lib/aws/iam/statement.js~statement#effect",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-effect",
    "lib/AWS/IAM/Statement.js~Statement#effect",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#effect",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-set-effect",
    "lib/AWS/IAM/Statement.js~Statement#effect",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#extract",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-method-extract",
    "lib/AWS/IAM/Statement.js~Statement#extract",
    "method"
  ],
  [
    "lib/aws/iam/statement.js~statement#notaction",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-notAction",
    "lib/AWS/IAM/Statement.js~Statement#notAction",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#notresource",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-notResource",
    "lib/AWS/IAM/Statement.js~Statement#notResource",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#principal",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-set-principal",
    "lib/AWS/IAM/Statement.js~Statement#principal",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#principal",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-principal",
    "lib/AWS/IAM/Statement.js~Statement#principal",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement#resource",
    "class/lib/AWS/IAM/Statement.js~Statement.html#instance-get-resource",
    "lib/AWS/IAM/Statement.js~Statement#resource",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement.allow",
    "class/lib/AWS/IAM/Statement.js~Statement.html#static-get-ALLOW",
    "lib/AWS/IAM/Statement.js~Statement.ALLOW",
    "member"
  ],
  [
    "lib/aws/iam/statement.js~statement.deny",
    "class/lib/AWS/IAM/Statement.js~Statement.html#static-get-DENY",
    "lib/AWS/IAM/Statement.js~Statement.DENY",
    "member"
  ],
  [
    "lib/aws/lambda/context.js",
    "file/lib/AWS/Lambda/Context.js.html",
    "lib/AWS/Lambda/Context.js",
    "file"
  ],
  [
    "lib/aws/lambda/context.js~context#constructor",
    "class/lib/AWS/Lambda/Context.js~Context.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Context.js~Context#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/context.js~context#getoption",
    "class/lib/AWS/Lambda/Context.js~Context.html#instance-method-getOption",
    "lib/AWS/Lambda/Context.js~Context#getOption",
    "method"
  ],
  [
    "lib/aws/lambda/context.js~context#has",
    "class/lib/AWS/Lambda/Context.js~Context.html#instance-method-has",
    "lib/AWS/Lambda/Context.js~Context#has",
    "method"
  ],
  [
    "lib/aws/lambda/context.js~context#options",
    "class/lib/AWS/Lambda/Context.js~Context.html#instance-get-options",
    "lib/AWS/Lambda/Context.js~Context#options",
    "member"
  ],
  [
    "lib/aws/lambda/errorresponse.js",
    "file/lib/AWS/Lambda/ErrorResponse.js.html",
    "lib/AWS/Lambda/ErrorResponse.js",
    "file"
  ],
  [
    "lib/aws/lambda/errorresponse.js~errorresponse#constructor",
    "class/lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.html#instance-constructor-constructor",
    "lib/AWS/Lambda/ErrorResponse.js~ErrorResponse#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/errorresponse.js~errorresponse.contextmethod",
    "class/lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.html#static-get-contextMethod",
    "lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.contextMethod",
    "member"
  ],
  [
    "lib/aws/lambda/errorresponse.js~errorresponse.createerrorobject",
    "class/lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.html#static-method-createErrorObject",
    "lib/AWS/Lambda/ErrorResponse.js~ErrorResponse.createErrorObject",
    "method"
  ],
  [
    "lib/aws/lambda/exception/contextalreadysentexception.js",
    "file/lib/AWS/Lambda/Exception/ContextAlreadySentException.js.html",
    "lib/AWS/Lambda/Exception/ContextAlreadySentException.js",
    "file"
  ],
  [
    "lib/aws/lambda/exception/contextalreadysentexception.js~contextalreadysentexception#constructor",
    "class/lib/AWS/Lambda/Exception/ContextAlreadySentException.js~ContextAlreadySentException.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Exception/ContextAlreadySentException.js~ContextAlreadySentException#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/exception/invalidcognitoidentityexception.js",
    "file/lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js.html",
    "lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js",
    "file"
  ],
  [
    "lib/aws/lambda/exception/invalidcognitoidentityexception.js~invalidcognitoidentityexception#constructor",
    "class/lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js~InvalidCognitoIdentityException.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Exception/InvalidCognitoIdentityException.js~InvalidCognitoIdentityException#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/exception/missingruntimecontextexception.js",
    "file/lib/AWS/Lambda/Exception/MissingRuntimeContextException.js.html",
    "lib/AWS/Lambda/Exception/MissingRuntimeContextException.js",
    "file"
  ],
  [
    "lib/aws/lambda/exception/missingruntimecontextexception.js~missingruntimecontextexception#constructor",
    "class/lib/AWS/Lambda/Exception/MissingRuntimeContextException.js~MissingRuntimeContextException.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Exception/MissingRuntimeContextException.js~MissingRuntimeContextException#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/exception/missingusercontextexception.js",
    "file/lib/AWS/Lambda/Exception/MissingUserContextException.js.html",
    "lib/AWS/Lambda/Exception/MissingUserContextException.js",
    "file"
  ],
  [
    "lib/aws/lambda/exception/missingusercontextexception.js~missingusercontextexception#constructor",
    "class/lib/AWS/Lambda/Exception/MissingUserContextException.js~MissingUserContextException.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Exception/MissingUserContextException.js~MissingUserContextException#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/request.js",
    "file/lib/AWS/Lambda/Request.js.html",
    "lib/AWS/Lambda/Request.js",
    "file"
  ],
  [
    "lib/aws/lambda/request.js~request#constructor",
    "class/lib/AWS/Lambda/Request.js~Request.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Request.js~Request#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/request.js~request#data",
    "class/lib/AWS/Lambda/Request.js~Request.html#instance-get-data",
    "lib/AWS/Lambda/Request.js~Request#data",
    "member"
  ],
  [
    "lib/aws/lambda/request.js~request#getparam",
    "class/lib/AWS/Lambda/Request.js~Request.html#instance-method-getParam",
    "lib/AWS/Lambda/Request.js~Request#getParam",
    "method"
  ],
  [
    "lib/aws/lambda/response.js",
    "file/lib/AWS/Lambda/Response.js.html",
    "lib/AWS/Lambda/Response.js",
    "file"
  ],
  [
    "lib/aws/lambda/response.js~response#constructor",
    "class/lib/AWS/Lambda/Response.js~Response.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Response.js~Response#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/response.js~response#contextsent",
    "class/lib/AWS/Lambda/Response.js~Response.html#instance-get-contextSent",
    "lib/AWS/Lambda/Response.js~Response#contextSent",
    "member"
  ],
  [
    "lib/aws/lambda/response.js~response#rawdata",
    "class/lib/AWS/Lambda/Response.js~Response.html#instance-get-rawData",
    "lib/AWS/Lambda/Response.js~Response#rawData",
    "member"
  ],
  [
    "lib/aws/lambda/response.js~response#runtime",
    "class/lib/AWS/Lambda/Response.js~Response.html#instance-get-runtime",
    "lib/AWS/Lambda/Response.js~Response#runtime",
    "member"
  ],
  [
    "lib/aws/lambda/response.js~response#send",
    "class/lib/AWS/Lambda/Response.js~Response.html#instance-method-send",
    "lib/AWS/Lambda/Response.js~Response#send",
    "method"
  ],
  [
    "lib/aws/lambda/response.js~response.contextmethod",
    "class/lib/AWS/Lambda/Response.js~Response.html#static-get-contextMethod",
    "lib/AWS/Lambda/Response.js~Response.contextMethod",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js",
    "file/lib/AWS/Lambda/Runtime.js.html",
    "lib/AWS/Lambda/Runtime.js",
    "file"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#calleeconfig",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-calleeConfig",
    "lib/AWS/Lambda/Runtime.js~Runtime#calleeConfig",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#constructor",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-constructor-constructor",
    "lib/AWS/Lambda/Runtime.js~Runtime#constructor",
    "method"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#context",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-context",
    "lib/AWS/Lambda/Runtime.js~Runtime#context",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#contextsent",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-contextSent",
    "lib/AWS/Lambda/Runtime.js~Runtime#contextSent",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#createerror",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-method-createError",
    "lib/AWS/Lambda/Runtime.js~Runtime#createError",
    "method"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#createresponse",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-method-createResponse",
    "lib/AWS/Lambda/Runtime.js~Runtime#createResponse",
    "method"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#forceuseridentity",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-forceUserIdentity",
    "lib/AWS/Lambda/Runtime.js~Runtime#forceUserIdentity",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#kernel",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-kernel",
    "lib/AWS/Lambda/Runtime.js~Runtime#kernel",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#lambda",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-lambda",
    "lib/AWS/Lambda/Runtime.js~Runtime#lambda",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#loggeduserid",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-loggedUserId",
    "lib/AWS/Lambda/Runtime.js~Runtime#loggedUserId",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#request",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-request",
    "lib/AWS/Lambda/Runtime.js~Runtime#request",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#run",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-method-run",
    "lib/AWS/Lambda/Runtime.js~Runtime#run",
    "method"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#securityservice",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-securityService",
    "lib/AWS/Lambda/Runtime.js~Runtime#securityService",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#validateinput",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-method-validateInput",
    "lib/AWS/Lambda/Runtime.js~Runtime#validateInput",
    "method"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime#validationschema",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#instance-get-validationSchema",
    "lib/AWS/Lambda/Runtime.js~Runtime#validationSchema",
    "member"
  ],
  [
    "lib/aws/lambda/runtime.js~runtime.validation_schemas_dir",
    "class/lib/AWS/Lambda/Runtime.js~Runtime.html#static-get-VALIDATION_SCHEMAS_DIR",
    "lib/AWS/Lambda/Runtime.js~Runtime.VALIDATION_SCHEMAS_DIR",
    "member"
  ],
  [
    "lib/aws/region.js",
    "file/lib/AWS/Region.js.html",
    "lib/AWS/Region.js",
    "file"
  ],
  [
    "lib/aws/region.js~region.any",
    "class/lib/AWS/Region.js~Region.html#static-get-ANY",
    "lib/AWS/Region.js~Region.ANY",
    "member"
  ],
  [
    "lib/aws/region.js~region.asia_pacific_seoul",
    "class/lib/AWS/Region.js~Region.html#static-get-ASIA_PACIFIC_SEOUL",
    "lib/AWS/Region.js~Region.ASIA_PACIFIC_SEOUL",
    "member"
  ],
  [
    "lib/aws/region.js~region.asia_pacific_singapore",
    "class/lib/AWS/Region.js~Region.html#static-get-ASIA_PACIFIC_SINGAPORE",
    "lib/AWS/Region.js~Region.ASIA_PACIFIC_SINGAPORE",
    "member"
  ],
  [
    "lib/aws/region.js~region.asia_pacific_sydney",
    "class/lib/AWS/Region.js~Region.html#static-get-ASIA_PACIFIC_SYDNEY",
    "lib/AWS/Region.js~Region.ASIA_PACIFIC_SYDNEY",
    "member"
  ],
  [
    "lib/aws/region.js~region.asia_pacific_tokyo",
    "class/lib/AWS/Region.js~Region.html#static-get-ASIA_PACIFIC_TOKYO",
    "lib/AWS/Region.js~Region.ASIA_PACIFIC_TOKYO",
    "member"
  ],
  [
    "lib/aws/region.js~region.eu_frankfurt",
    "class/lib/AWS/Region.js~Region.html#static-get-EU_FRANKFURT",
    "lib/AWS/Region.js~Region.EU_FRANKFURT",
    "member"
  ],
  [
    "lib/aws/region.js~region.eu_ireland",
    "class/lib/AWS/Region.js~Region.html#static-get-EU_IRELAND",
    "lib/AWS/Region.js~Region.EU_IRELAND",
    "member"
  ],
  [
    "lib/aws/region.js~region.south_america_sao_paulo",
    "class/lib/AWS/Region.js~Region.html#static-get-SOUTH_AMERICA_SAO_PAULO",
    "lib/AWS/Region.js~Region.SOUTH_AMERICA_SAO_PAULO",
    "member"
  ],
  [
    "lib/aws/region.js~region.us_east_n_virginia",
    "class/lib/AWS/Region.js~Region.html#static-get-US_EAST_N_VIRGINIA",
    "lib/AWS/Region.js~Region.US_EAST_N_VIRGINIA",
    "member"
  ],
  [
    "lib/aws/region.js~region.us_west_n_california",
    "class/lib/AWS/Region.js~Region.html#static-get-US_WEST_N_CALIFORNIA",
    "lib/AWS/Region.js~Region.US_WEST_N_CALIFORNIA",
    "member"
  ],
  [
    "lib/aws/region.js~region.us_west_oregon",
    "class/lib/AWS/Region.js~Region.html#static-get-US_WEST_OREGON",
    "lib/AWS/Region.js~Region.US_WEST_OREGON",
    "member"
  ],
  [
    "lib/aws/region.js~region.all",
    "class/lib/AWS/Region.js~Region.html#static-method-all",
    "lib/AWS/Region.js~Region.all",
    "method"
  ],
  [
    "lib/aws/region.js~region.exists",
    "class/lib/AWS/Region.js~Region.html#static-method-exists",
    "lib/AWS/Region.js~Region.exists",
    "method"
  ],
  [
    "lib/aws/region.js~region.getappropriateawsregion",
    "class/lib/AWS/Region.js~Region.html#static-method-getAppropriateAwsRegion",
    "lib/AWS/Region.js~Region.getAppropriateAwsRegion",
    "method"
  ],
  [
    "lib/aws/region.js~region.list",
    "class/lib/AWS/Region.js~Region.html#static-method-list",
    "lib/AWS/Region.js~Region.list",
    "method"
  ],
  [
    "lib/aws/service.js",
    "file/lib/AWS/Service.js.html",
    "lib/AWS/Service.js",
    "file"
  ],
  [
    "lib/aws/service.js~service.any",
    "class/lib/AWS/Service.js~Service.html#static-get-ANY",
    "lib/AWS/Service.js~Service.ANY",
    "member"
  ],
  [
    "lib/aws/service.js~service.api_gateway",
    "class/lib/AWS/Service.js~Service.html#static-get-API_GATEWAY",
    "lib/AWS/Service.js~Service.API_GATEWAY",
    "member"
  ],
  [
    "lib/aws/service.js~service.api_gateway_execute",
    "class/lib/AWS/Service.js~Service.html#static-get-API_GATEWAY_EXECUTE",
    "lib/AWS/Service.js~Service.API_GATEWAY_EXECUTE",
    "member"
  ],
  [
    "lib/aws/service.js~service.cloud_front",
    "class/lib/AWS/Service.js~Service.html#static-get-CLOUD_FRONT",
    "lib/AWS/Service.js~Service.CLOUD_FRONT",
    "member"
  ],
  [
    "lib/aws/service.js~service.cloud_search",
    "class/lib/AWS/Service.js~Service.html#static-get-CLOUD_SEARCH",
    "lib/AWS/Service.js~Service.CLOUD_SEARCH",
    "member"
  ],
  [
    "lib/aws/service.js~service.cloud_watch_logs",
    "class/lib/AWS/Service.js~Service.html#static-get-CLOUD_WATCH_LOGS",
    "lib/AWS/Service.js~Service.CLOUD_WATCH_LOGS",
    "member"
  ],
  [
    "lib/aws/service.js~service.cognito_identity",
    "class/lib/AWS/Service.js~Service.html#static-get-COGNITO_IDENTITY",
    "lib/AWS/Service.js~Service.COGNITO_IDENTITY",
    "member"
  ],
  [
    "lib/aws/service.js~service.cognito_sync",
    "class/lib/AWS/Service.js~Service.html#static-get-COGNITO_SYNC",
    "lib/AWS/Service.js~Service.COGNITO_SYNC",
    "member"
  ],
  [
    "lib/aws/service.js~service.dynamo_db",
    "class/lib/AWS/Service.js~Service.html#static-get-DYNAMO_DB",
    "lib/AWS/Service.js~Service.DYNAMO_DB",
    "member"
  ],
  [
    "lib/aws/service.js~service.elastic_cache",
    "class/lib/AWS/Service.js~Service.html#static-get-ELASTIC_CACHE",
    "lib/AWS/Service.js~Service.ELASTIC_CACHE",
    "member"
  ],
  [
    "lib/aws/service.js~service.identity_and_access_management",
    "class/lib/AWS/Service.js~Service.html#static-get-IDENTITY_AND_ACCESS_MANAGEMENT",
    "lib/AWS/Service.js~Service.IDENTITY_AND_ACCESS_MANAGEMENT",
    "member"
  ],
  [
    "lib/aws/service.js~service.kinesis",
    "class/lib/AWS/Service.js~Service.html#static-get-KINESIS",
    "lib/AWS/Service.js~Service.KINESIS",
    "member"
  ],
  [
    "lib/aws/service.js~service.lambda",
    "class/lib/AWS/Service.js~Service.html#static-get-LAMBDA",
    "lib/AWS/Service.js~Service.LAMBDA",
    "member"
  ],
  [
    "lib/aws/service.js~service.security_token_service",
    "class/lib/AWS/Service.js~Service.html#static-get-SECURITY_TOKEN_SERVICE",
    "lib/AWS/Service.js~Service.SECURITY_TOKEN_SERVICE",
    "member"
  ],
  [
    "lib/aws/service.js~service.simple_notification_service",
    "class/lib/AWS/Service.js~Service.html#static-get-SIMPLE_NOTIFICATION_SERVICE",
    "lib/AWS/Service.js~Service.SIMPLE_NOTIFICATION_SERVICE",
    "member"
  ],
  [
    "lib/aws/service.js~service.simple_queue_service",
    "class/lib/AWS/Service.js~Service.html#static-get-SIMPLE_QUEUE_SERVICE",
    "lib/AWS/Service.js~Service.SIMPLE_QUEUE_SERVICE",
    "member"
  ],
  [
    "lib/aws/service.js~service.simple_storage_service",
    "class/lib/AWS/Service.js~Service.html#static-get-SIMPLE_STORAGE_SERVICE",
    "lib/AWS/Service.js~Service.SIMPLE_STORAGE_SERVICE",
    "member"
  ],
  [
    "lib/aws/service.js~service.exists",
    "class/lib/AWS/Service.js~Service.html#static-method-exists",
    "lib/AWS/Service.js~Service.exists",
    "method"
  ],
  [
    "lib/aws/service.js~service.identifier",
    "class/lib/AWS/Service.js~Service.html#static-method-identifier",
    "lib/AWS/Service.js~Service.identifier",
    "method"
  ],
  [
    "lib/aws/service.js~service.list",
    "class/lib/AWS/Service.js~Service.html#static-method-list",
    "lib/AWS/Service.js~Service.list",
    "method"
  ],
  [
    "lib/exception/databaseoperationexception.js",
    "file/lib/Exception/DatabaseOperationException.js.html",
    "lib/Exception/DatabaseOperationException.js",
    "file"
  ],
  [
    "lib/exception/databaseoperationexception.js~databaseoperationexception#constructor",
    "class/lib/Exception/DatabaseOperationException.js~DatabaseOperationException.html#instance-constructor-constructor",
    "lib/Exception/DatabaseOperationException.js~DatabaseOperationException#constructor",
    "method"
  ],
  [
    "lib/exception/exception.js",
    "file/lib/Exception/Exception.js.html",
    "lib/Exception/Exception.js",
    "file"
  ],
  [
    "lib/exception/exception.js~exception#constructor",
    "class/lib/Exception/Exception.js~Exception.html#instance-constructor-constructor",
    "lib/Exception/Exception.js~Exception#constructor",
    "method"
  ],
  [
    "lib/exception/exception.js~exception#name",
    "class/lib/Exception/Exception.js~Exception.html#instance-get-name",
    "lib/Exception/Exception.js~Exception#name",
    "member"
  ],
  [
    "lib/exception/invalidargumentexception.js",
    "file/lib/Exception/InvalidArgumentException.js.html",
    "lib/Exception/InvalidArgumentException.js",
    "file"
  ],
  [
    "lib/exception/invalidargumentexception.js~invalidargumentexception#constructor",
    "class/lib/Exception/InvalidArgumentException.js~InvalidArgumentException.html#instance-constructor-constructor",
    "lib/Exception/InvalidArgumentException.js~InvalidArgumentException#constructor",
    "method"
  ],
  [
    "lib/exception/methodsnotimplementedexception.js",
    "file/lib/Exception/MethodsNotImplementedException.js.html",
    "lib/Exception/MethodsNotImplementedException.js",
    "file"
  ],
  [
    "lib/exception/methodsnotimplementedexception.js~methodsnotimplementedexception#constructor",
    "class/lib/Exception/MethodsNotImplementedException.js~MethodsNotImplementedException.html#instance-constructor-constructor",
    "lib/Exception/MethodsNotImplementedException.js~MethodsNotImplementedException#constructor",
    "method"
  ],
  [
    "lib/generic/methodsproxy.js",
    "file/lib/Generic/MethodsProxy.js.html",
    "lib/Generic/MethodsProxy.js",
    "file"
  ],
  [
    "lib/generic/methodsproxy.js~methodsproxy#constructor",
    "class/lib/Generic/MethodsProxy.js~MethodsProxy.html#instance-constructor-constructor",
    "lib/Generic/MethodsProxy.js~MethodsProxy#constructor",
    "method"
  ],
  [
    "lib/generic/methodsproxy.js~methodsproxy#proxy",
    "class/lib/Generic/MethodsProxy.js~MethodsProxy.html#instance-method-proxy",
    "lib/Generic/MethodsProxy.js~MethodsProxy#proxy",
    "method"
  ],
  [
    "lib/generic/methodsproxy.js~methodsproxy#proxyoverride",
    "class/lib/Generic/MethodsProxy.js~MethodsProxy.html#instance-method-proxyOverride",
    "lib/Generic/MethodsProxy.js~MethodsProxy#proxyOverride",
    "method"
  ],
  [
    "lib/generic/methodsproxy.js~methodsproxy#target",
    "class/lib/Generic/MethodsProxy.js~MethodsProxy.html#instance-get-target",
    "lib/Generic/MethodsProxy.js~MethodsProxy#target",
    "member"
  ],
  [
    "lib/generic/objectstorage.js",
    "file/lib/Generic/ObjectStorage.js.html",
    "lib/Generic/ObjectStorage.js",
    "file"
  ],
  [
    "lib/generic/objectstorage.js~objectstorage#add",
    "class/lib/Generic/ObjectStorage.js~ObjectStorage.html#instance-method-add",
    "lib/Generic/ObjectStorage.js~ObjectStorage#add",
    "method"
  ],
  [
    "lib/generic/objectstorage.js~objectstorage#constructor",
    "class/lib/Generic/ObjectStorage.js~ObjectStorage.html#instance-constructor-constructor",
    "lib/Generic/ObjectStorage.js~ObjectStorage#constructor",
    "method"
  ],
  [
    "lib/generic/objectstorage.js~objectstorage#find",
    "class/lib/Generic/ObjectStorage.js~ObjectStorage.html#instance-method-find",
    "lib/Generic/ObjectStorage.js~ObjectStorage#find",
    "method"
  ],
  [
    "lib/generic/objectstorage.js~objectstorage#iterator",
    "class/lib/Generic/ObjectStorage.js~ObjectStorage.html#instance-get-iterator",
    "lib/Generic/ObjectStorage.js~ObjectStorage#iterator",
    "member"
  ],
  [
    "lib/generic/objectvector.js",
    "file/lib/Generic/ObjectVector.js.html",
    "lib/Generic/ObjectVector.js",
    "file"
  ],
  [
    "lib/generic/objectvector.js~objectvector#add",
    "class/lib/Generic/ObjectVector.js~ObjectVector.html#instance-method-add",
    "lib/Generic/ObjectVector.js~ObjectVector#add",
    "method"
  ],
  [
    "lib/generic/objectvector.js~objectvector#collection",
    "class/lib/Generic/ObjectVector.js~ObjectVector.html#instance-get-collection",
    "lib/Generic/ObjectVector.js~ObjectVector#collection",
    "member"
  ],
  [
    "lib/generic/objectvector.js~objectvector#constructor",
    "class/lib/Generic/ObjectVector.js~ObjectVector.html#instance-constructor-constructor",
    "lib/Generic/ObjectVector.js~ObjectVector#constructor",
    "method"
  ],
  [
    "lib/oop/interface.js",
    "file/lib/OOP/Interface.js.html",
    "lib/OOP/Interface.js",
    "file"
  ],
  [
    "lib/oop/interface.js~interface#constructor",
    "class/lib/OOP/Interface.js~Interface.html#instance-constructor-constructor",
    "lib/OOP/Interface.js~Interface#constructor",
    "method"
  ],
  [
    "lib/runtime/sandbox.js",
    "file/lib/Runtime/Sandbox.js.html",
    "lib/Runtime/Sandbox.js",
    "file"
  ],
  [
    "lib/runtime/sandbox.js~sandbox#constructor",
    "class/lib/Runtime/Sandbox.js~Sandbox.html#instance-constructor-constructor",
    "lib/Runtime/Sandbox.js~Sandbox#constructor",
    "method"
  ],
  [
    "lib/runtime/sandbox.js~sandbox#fail",
    "class/lib/Runtime/Sandbox.js~Sandbox.html#instance-method-fail",
    "lib/Runtime/Sandbox.js~Sandbox#fail",
    "method"
  ],
  [
    "lib/runtime/sandbox.js~sandbox#func",
    "class/lib/Runtime/Sandbox.js~Sandbox.html#instance-get-func",
    "lib/Runtime/Sandbox.js~Sandbox#func",
    "member"
  ],
  [
    "lib/runtime/sandbox.js~sandbox#run",
    "class/lib/Runtime/Sandbox.js~Sandbox.html#instance-method-run",
    "lib/Runtime/Sandbox.js~Sandbox#run",
    "method"
  ],
  [
    "lib/runtime/sandbox.js~sandbox.on_fail_cb",
    "class/lib/Runtime/Sandbox.js~Sandbox.html#static-get-ON_FAIL_CB",
    "lib/Runtime/Sandbox.js~Sandbox.ON_FAIL_CB",
    "member"
  ],
  [
    "lib/bootstrap.js",
    "file/lib/bootstrap.js.html",
    "lib/bootstrap.js",
    "file"
  ]
]