window.esdocSearchIndex = [
  [
    "deep-fs/lib/exception/exception.js~exception",
    "class/lib/Exception/Exception.js~Exception.html",
    "<span>Exception</span> <span class=\"search-result-import-path\">deep-fs/lib/Exception/Exception.js</span>",
    "class"
  ],
  [
    "deep-fs/lib/fs.js~fs",
    "class/lib/FS.js~FS.html",
    "<span>FS</span> <span class=\"search-result-import-path\">deep-fs/lib/FS.js</span>",
    "class"
  ],
  [
    "deep-fs/lib/registry.js~registry",
    "class/lib/Registry.js~Registry.html",
    "<span>Registry</span> <span class=\"search-result-import-path\">deep-fs/lib/Registry.js</span>",
    "class"
  ],
  [
    "deep-fs/lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html",
    "<span>S3FSRelativeFSExtender</span> <span class=\"search-result-import-path\">deep-fs/lib/Local/S3FSRelativeFSExtender.js</span>",
    "class"
  ],
  [
    "deep-fs/lib/exception/unknownfolderexception.js~unknownfolderexception",
    "class/lib/Exception/UnknownFolderException.js~UnknownFolderException.html",
    "<span>UnknownFolderException</span> <span class=\"search-result-import-path\">deep-fs/lib/Exception/UnknownFolderException.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/exception/exception.js",
    "file/lib/Exception/Exception.js.html",
    "lib/Exception/Exception.js",
    "file"
  ],
  [
    "lib/exception/exception.js~exception#constructor",
    "class/lib/Exception/Exception.js~Exception.html#instance-constructor-constructor",
    "lib/Exception/Exception.js~Exception#constructor",
    "method"
  ],
  [
    "lib/exception/unknownfolderexception.js",
    "file/lib/Exception/UnknownFolderException.js.html",
    "lib/Exception/UnknownFolderException.js",
    "file"
  ],
  [
    "lib/exception/unknownfolderexception.js~unknownfolderexception#constructor",
    "class/lib/Exception/UnknownFolderException.js~UnknownFolderException.html#instance-constructor-constructor",
    "lib/Exception/UnknownFolderException.js~UnknownFolderException#constructor",
    "method"
  ],
  [
    "lib/fs.js",
    "file/lib/FS.js.html",
    "lib/FS.js",
    "file"
  ],
  [
    "lib/fs.js~fs#boot",
    "class/lib/FS.js~FS.html#instance-method-boot",
    "lib/FS.js~FS#boot",
    "method"
  ],
  [
    "lib/fs.js~fs#constructor",
    "class/lib/FS.js~FS.html#instance-constructor-constructor",
    "lib/FS.js~FS#constructor",
    "method"
  ],
  [
    "lib/fs.js~fs#getfolder",
    "class/lib/FS.js~FS.html#instance-method-getFolder",
    "lib/FS.js~FS#getFolder",
    "method"
  ],
  [
    "lib/fs.js~fs#public",
    "class/lib/FS.js~FS.html#instance-get-public",
    "lib/FS.js~FS#public",
    "member"
  ],
  [
    "lib/fs.js~fs#registry",
    "class/lib/FS.js~FS.html#instance-get-registry",
    "lib/FS.js~FS#registry",
    "member"
  ],
  [
    "lib/fs.js~fs#system",
    "class/lib/FS.js~FS.html#instance-get-system",
    "lib/FS.js~FS#system",
    "member"
  ],
  [
    "lib/fs.js~fs#tmp",
    "class/lib/FS.js~FS.html#instance-get-tmp",
    "lib/FS.js~FS#tmp",
    "member"
  ],
  [
    "lib/fs.js~fs.folders",
    "class/lib/FS.js~FS.html#static-get-FOLDERS",
    "lib/FS.js~FS.FOLDERS",
    "member"
  ],
  [
    "lib/fs.js~fs.public",
    "class/lib/FS.js~FS.html#static-get-PUBLIC",
    "lib/FS.js~FS.PUBLIC",
    "member"
  ],
  [
    "lib/fs.js~fs.registryinstance",
    "class/lib/FS.js~FS.html#static-get-RegistryInstance",
    "lib/FS.js~FS.RegistryInstance",
    "member"
  ],
  [
    "lib/fs.js~fs.system",
    "class/lib/FS.js~FS.html#static-get-SYSTEM",
    "lib/FS.js~FS.SYSTEM",
    "member"
  ],
  [
    "lib/fs.js~fs.tmp",
    "class/lib/FS.js~FS.html#static-get-TMP",
    "lib/FS.js~FS.TMP",
    "member"
  ],
  [
    "lib/local/s3fsrelativefsextender.js",
    "file/lib/Local/S3FSRelativeFSExtender.js.html",
    "lib/Local/S3FSRelativeFSExtender.js",
    "file"
  ],
  [
    "lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender#extend_object",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html#instance-get-EXTEND_OBJECT",
    "lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender#EXTEND_OBJECT",
    "member"
  ],
  [
    "lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender#constructor",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html#instance-constructor-constructor",
    "lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender#constructor",
    "method"
  ],
  [
    "lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender#cwd",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html#instance-get-cwd",
    "lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender#cwd",
    "member"
  ],
  [
    "lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender#relativefs",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html#instance-get-relativeFs",
    "lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender#relativeFs",
    "member"
  ],
  [
    "lib/local/s3fsrelativefsextender.js~s3fsrelativefsextender#relativefsextended",
    "class/lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender.html#instance-get-relativeFsExtended",
    "lib/Local/S3FSRelativeFSExtender.js~S3FSRelativeFSExtender#relativeFsExtended",
    "member"
  ],
  [
    "lib/registry.js",
    "file/lib/Registry.js.html",
    "lib/Registry.js",
    "file"
  ],
  [
    "lib/registry.js~registry#bucket",
    "class/lib/Registry.js~Registry.html#instance-get-bucket",
    "lib/Registry.js~Registry#bucket",
    "member"
  ],
  [
    "lib/registry.js~registry#constructor",
    "class/lib/Registry.js~Registry.html#instance-constructor-constructor",
    "lib/Registry.js~Registry#constructor",
    "method"
  ],
  [
    "lib/registry.js~registry#ensurefresh",
    "class/lib/Registry.js~Registry.html#instance-set-ensureFresh",
    "lib/Registry.js~Registry#ensureFresh",
    "member"
  ],
  [
    "lib/registry.js~registry#ensurefresh",
    "class/lib/Registry.js~Registry.html#instance-get-ensureFresh",
    "lib/Registry.js~Registry#ensureFresh",
    "member"
  ],
  [
    "lib/registry.js~registry#exists",
    "class/lib/Registry.js~Registry.html#instance-method-exists",
    "lib/Registry.js~Registry#exists",
    "method"
  ],
  [
    "lib/registry.js~registry#keys",
    "class/lib/Registry.js~Registry.html#instance-method-keys",
    "lib/Registry.js~Registry#keys",
    "method"
  ],
  [
    "lib/registry.js~registry#lastmodified",
    "class/lib/Registry.js~Registry.html#instance-get-lastModified",
    "lib/Registry.js~Registry#lastModified",
    "member"
  ],
  [
    "lib/registry.js~registry#read",
    "class/lib/Registry.js~Registry.html#instance-method-read",
    "lib/Registry.js~Registry#read",
    "method"
  ],
  [
    "lib/registry.js~registry#refresh",
    "class/lib/Registry.js~Registry.html#instance-method-refresh",
    "lib/Registry.js~Registry#refresh",
    "method"
  ],
  [
    "lib/registry.js~registry#registryfile",
    "class/lib/Registry.js~Registry.html#instance-get-registryFile",
    "lib/Registry.js~Registry#registryFile",
    "member"
  ],
  [
    "lib/registry.js~registry#s3",
    "class/lib/Registry.js~Registry.html#instance-get-s3",
    "lib/Registry.js~Registry#s3",
    "member"
  ],
  [
    "lib/registry.js~registry#write",
    "class/lib/Registry.js~Registry.html#instance-method-write",
    "lib/Registry.js~Registry#write",
    "method"
  ],
  [
    "lib/registry.js~registry.ensure_fresh",
    "class/lib/Registry.js~Registry.html#static-get-ENSURE_FRESH",
    "lib/Registry.js~Registry.ENSURE_FRESH",
    "member"
  ],
  [
    "lib/registry.js~registry.registry_file",
    "class/lib/Registry.js~Registry.html#static-get-REGISTRY_FILE",
    "lib/Registry.js~Registry.REGISTRY_FILE",
    "member"
  ],
  [
    "lib/registry.js~registry.createfromfs",
    "class/lib/Registry.js~Registry.html#static-method-createFromFS",
    "lib/Registry.js~Registry.createFromFS",
    "method"
  ],
  [
    "lib/bootstrap.js",
    "file/lib/bootstrap.js.html",
    "lib/bootstrap.js",
    "file"
  ]
]