/**
 * Created by vcernomschi on 11/24/15.
 */
export default {
  secretAccessKey: 'dgd34rgdfs45r568356sadasdaskjkj',
  expired: false,
  expireTime: '2016-12-20T17:24:07.000Z',
  accessKeyId: '78464j4o5ktpsgoguecgt',
  sessionToken: 'AQoDYXdzMFG//////////wEasAUcsAsb0kzbFk1VUOwZVl8F7IGk7JS++suLw9uXRhR97+PTDywnDI1PZXs2bJV/5tRCp',
  params: {
    IdentityPoolId: 'us-east-1:7e2e9d57-wswed-asdasdas-22f4-595e1d8128c5',
    RoleSessionName: 'web-identity',
    IdentityId: 'us-east-1:b5487645-61bd-4c3b-dd54-5cba66070e7c',
  },
  data: {
    IdentityId: 'us-east-1:saadasdas-61bd-4c3b-asdasda-5cba66070e7c',
    Credentials: {
      AccessKeyId: 'ASIAJ76WBDMQ633S2EIA',
      SecretKey: '45645knlaskdasdasd',
      SessionToken: 'AQoDYXdzMFG//////////wEasAUcsAsb0kzbFk1VUOwZVl8F7IGk7JS++suLw9uXRhR97+PTDywnDI1PZXs2bJV/5tRCp',
      Expiration: '2015-11-20T17:24:07.000Z',
    },
  },
  identityId: 'us-east-1:b5487645-61bd-4c3b-dd54-sdasasdas',
  webIdentityCredentials: {
    expired: true,
    expireTime: null,
    params: {
      IdentityPoolId: 'us-east-1:7e2e9d57-wswed-asdasdasd-22f4-595e1d8128c5',
      RoleSessionName: 'web-identity',
      IdentityId: 'us-east-1:b5487645-61bd-4c3b-asdasda-5cba66070e7c',
    },
    data: null,
  },
  cognito: {
    config: {
      credentials: null,
      credentialProvider: null,
      region: 'us-east-1',
      logger: null,
      apiVersions: {},
      apiVersion: null,
      endpoint: 'cognito-identity.us-east-1.amazonaws.com',
      httpOptions: {
        timeout: 120000,
      },
      maxRetries: 3,
      maxRedirects: 10,
      paramValidation: true,
      sslEnabled: true,
      s3ForcePathStyle: false,
      s3BucketEndpoint: false,
      computeChecksums: true,
      convertResponseTypes: true,
      correctClockSkew: false,
      dynamoDbCrc32: true,
      systemClockOffset: 0,
      signatureVersion: 'v4',
      signatureCache: true,
      params: {
        IdentityPoolId: 'us-east-1:7e2e9d57-wswed-4893-22f4-595e1d8128c5',
        RoleSessionName: 'web-identity',
        IdentityId: 'us-east-1:b5487645-61bd-4c3b-dd54-5cba66070e7c',
      },
    },
    isGlobalEndpoint: false,
    endpoint: {
      protocol: 'https:',
      host: 'cognito-identity.us-east-1.amazonaws.com',
      port: 443,
      hostname: 'cognito-identity.us-east-1.amazonaws.com',
      pathname: '/',
      path: '/',
      href: 'https://cognito-identity.us-east-1.amazonaws.com/',
    },
  },
  sts: {
    config: {
      credentials: null,
      credentialProvider: null,
      region: null,
      logger: null,
      apiVersions: {},
      apiVersion: null,
      endpoint: 'https://sts.amazonaws.com',
      httpOptions: {
        timeout: 120000
      },
      maxRetries: 3,
      maxRedirects: 10,
      paramValidation: true,
      sslEnabled: true,
      s3ForcePathStyle: false,
      s3BucketEndpoint: false,
      computeChecksums: true,
      convertResponseTypes: true,
      correctClockSkew: false,
      dynamoDbCrc32: true,
      systemClockOffset: 0,
      signatureVersion: 'v4',
      signatureCache: true
    },
    isGlobalEndpoint: true,
    endpoint: {
      protocol: 'https:',
      host: 'sts.amazonaws.com',
      port: 443,
      hostname: 'sts.amazonaws.com',
      pathname: '/',
      path: '/',
      href: 'https://sts.amazonaws.com/',
    },
  },
};
